### ISSUE TITLE
Map Chunk Analysis/Suggestions?

### ISSUE THREAD

**Issue by vintagedon** [orphu/mcdungeon#158]
Currently, the only way to find out how many "good chunks" you have for placement is to actually input your data and do a generation.  Right before it begins it's placement, it lets you know how many good chunks you have.  It would be nice to have an analysis mode that would let you know how many good chunks you have, and based upon the max dimension of the dungeons that you put in, give you a rough idea of how many dungeons you could place at -1, and then perhaps numbers for various distances between them.

To expand some, Although on very large maps analysis takes a long time (I'm doing a 400,000+ chunk map with all custom biomes, many of them with a height that invalidates them for placement), it might be nice to know how many dungeons I'm looking at placing prior to the placement.  For example, I don't really want, on this particular map, to do a -1 placement.  I'd rather be able to say ... ok, at a maximum size of 7x7, I can fit around X number of dungeons on the map. and if I want them to be Y number of chunks apart at minimum, I need to place Z number of dungeons.  There's likely no way to be precise, since in a range you never know what you're getting, but a ball park based on the maximum size would be nice.

**Comment by JiFish** [comment]
Closing since issue #147 is closed.
