### ISSUE TITLE
Blacksmiths wander away from Forge landmarks

### ISSUE THREAD

**Issue by orphu** [orphu/mcdungeon#247]
Might be good to build it such that they can't get away. Also zombies are likely to eat them if there is a clear path. 

![2014-09-01_13 09 21](https://cloud.githubusercontent.com/assets/651179/4110957/aa7e143c-31fb-11e4-8abc-a8c8745dfa35.png)

**Comment by sshipway** [comment]
Now that #250 is merged, I think this can be closed
