### ISSUE TITLE
Utility functions to build JSON formatted text

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#253]
Utility functions to build JSON formatted text as outlined here: http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/351959-1-7-1-8-raw-json-text-examples-for-tellraw-title

Possibility using the standard python json library?

**Comment by orphu** [comment]
Added a very basic stub to deal with the DV book encoding issue. 

This should be expanded to handle formatting and effects.

**Comment by orphu** [comment]
Took a minimal approach to this. The built-in Python JSON lib seems to do a good job formatting things. 

The encode function will take a string or a dict. If a string, it will construct the "text" tag and encode automatically. If you pass a dict, it will be encoded using the JSON parser. See the shop flyer for an example.

**Comment by JiFish** [comment]
Keep it simple. Good idea.
