### ISSUE TITLE
genpoi is unable to identify the true entrance location for Pyramid entrances

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#255]
For some reason, on dungeons with Pyramid entrances, the genpoi landmark location is incorrectly placed to the SE of the actual stairway location.  This appears to affect all Pyramid entrances but not any other types of entrance.  Tested with 0.13 and 0.14 dungeons and in both cases only the pyramid entrance is affected.

**Comment by sshipway** [comment]
I would agree with making the maze portal_exit equal to the maze entrance.  This would make the genpoi location more logical as well.  Did that ever happen?

**Comment by JiFish** [comment]
Nope. That should probably be spun out to it's own issue.
