### ISSUE TITLE
Remove overviewer code

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#265]
Remove overviewer code and replace with a biome lookup via pymclevel.

It would be useful to know if we are going to switch to the https://github.com/Khroki/pymclevel branch. For the moment, I will use the direct-access method which will work in both.

This will hopefully fix #85 at the same time.

**Comment by JiFish** [comment]
Finally got a chance to really look at this.

Overviewer is used to generate the dungeon/hunts cache. I was not excepting that. Shouldn't be a problem to switch this to pymclevel too... except I can figure out if pymclevel's ``getTimestamp`` is equivalent to overviewer's ``get_chunk_timestamp``. Any idea @orphu?

**Comment by orphu** [comment]
Yeah, overviewer isn't used for much. It was used back when pymclevel did not support biome data and the prospects of pymclevel adding it seemed slim. It's only used to extract biome data and check the freshness of a chunk against the cache IIRC. 

If pymclevel supports both of these then it should be easy to remove overviewer. Will we need to move to the unified version of pymclevel to get these functions?

**Comment by JiFish** [comment]
unified is not required. Apparently, use can just do this:
```
        chunk = level.getChunk(x /16, z / 16)
        array = chunk.root_tag["Level"]["Biomes"].value
```

However there is a nice wrapper for this in the unified version: https://github.com/Iciciliser/MCEdit-Unified/commit/6485c02239ac914cae22ff72d26241e145dc65f2

**Comment by orphu** [comment]
Cool. As far as timestamp, should be easy to just read a known map with both and find out. :) 

I'll see if I can do some experimenting this weekend.

**Comment by JiFish** [comment]
If you wanted to take this one off my hands, I certainly wouldn't object. :)

**Comment by orphu** [comment]
This needs more testing.

**Comment by orphu** [comment]
Biomes was even easier. This gives you a 2d numpy array:

biomes = chunk.Biomes

Chunk Timestamp got weird. There might be a better way.

**Comment by JiFish** [comment]
Nice! This has really cleaned things up.

**Comment by orphu** [comment]
I know, right? It's about time on this one. 

Once I started looking into the DataVersion issue and changing how the caches work I really wanted to do this first before digging the hole deeper.
