### ISSUE TITLE
Mac version crashing on boot.

### ISSUE THREAD

**Issue by AmbassadorPineapple** [orphu/mcdungeon#269]
I keep trying to load the program. At v0.13.0, the program worked fine. After that, it went and died. In a pit. My error report is this "/mcdungeon-v0.14.1-macosx64/launcher.command: line 3:  7794 Segmentation fault: 11  ./mcdungeon interactive
Press any key to exit...". I chose not to include the file pathing because I don't want the internet to know more about me than it already does. If it helps, I'm using a Macbook from 2008. Please help me! I love this program!

**Comment by bartczam** [comment]
I wish I knew the answer too, I am getting mysterious "Segmentation fault 11" error. Nothing happens.

**Comment by JiFish** [comment]
Are you also using the mac version? Please provide detail if you can.

**Comment by bartczam** [comment]
Yes, I'm using a MAC version

My software versions are: OSX 10.8.5, Python 2.7.9

I found a workaround:
a) Do not use the mac versions, use python source versions
b) Install numpy if not present (by using console command: pip install numpy)
c) Run the code through python itself, like python mcdungeon.py interactive

It works fine then

**Comment by orphu** [comment]
The frozen MAC version likely requires 10.9 OR 10.10. I'll be more clear about those requirements in the future.

**Comment by orphu** [comment]
Closing this one, as it's just an issue with OSX required versions.
