### ISSUE TITLE
Can I specify the theme for a dungeon using add command?

### ISSUE THREAD

**Issue by dls314159** [orphu/mcdungeon#272]
I see that there were changes to add a pirate theme not tied to a biome, is there a way to specify that theme or another theme when using the add command to mcdungeon?

**Comment by sshipway** [comment]
The 'pirate' naming theme was added for the benefit of the Treasure Hunts, which always use it to determine the hunt name.  
On dungeons, I believe, the naming cheme is tied to the entrance type (which is also tied to the biome), and there are no entrance types associated with pirates... so it would be maybe problematic to specify the naming scheme as this would have implications for the dungeon creation.  I'd have to take another look at the code to be sure.

**Comment by JiFish** [comment]
sshipway is correct, pirates naming is intended for treasure hunts only and doesn't have a theme associated with it. What kind of pirate would be a temple or dungeon, after all? :p

Maybe in the future we can come up with some sort of sunken ship entrance type for a pirate theme. But at the moment, this can't be done without messing with the source.

**Comment by sshipway** [comment]
I rather like the idea of a wrecked ship being the entrance, in a seashore biome.  Wouldn't make sense anywhere else.  Pirates could also have a stronghold (small castle).  Possibly make it use pirate theme for these but they can only be in a seashore biome?

**Comment by JiFish** [comment]
I'm going to go ahead and close this. If anyone wants to add any of the ideas here as a feature request, feel free.
