### ISSUE TITLE
Add info to the FAQ about python installation

### ISSUE THREAD

**Issue by dls314159** [orphu/mcdungeon#273]
It wasn't trivial to figure out how to get a 64-bit installation of python on Windows given that numpy is hard to find.

I found that WinPython was a good way to go. I think the info would be helpful.

Pointing out that 64-bit python is necessary for larger dungeons would be good, too.

**Comment by AmbassadorPineapple** [comment]
Can you also add an installation guide for NumPy? I am stumped as F*CK on installing the thing. Jeez.

**Comment by JiFish** [comment]
If somebody wants to provide a guide, we'd be happy to add it. The python version is really for people that know what they are doing, so there isn't much documentation there.

> Can you also add an installation guide for NumPy? I am stumped as F*CK on installing the thing. Jeez.

I feel your pain, but this would be better directed towards the NumPy team. I 100% agree that the install is confusing.

**Comment by dls314159** [comment]
I gave up trying to build my own NumPy or find it packaged for the python.org 64-bit python distribution. But mcdungeon seems happy with the python distribution from http://winpython.github.io/

**Comment by dls314159** [comment]
Closing the issue. I'll try to find a forum login to post there instead.
