### ISSUE TITLE
TypeError on add

### ISSUE THREAD

**Issue by jjaquinta** [orphu/mcdungeon#275]
Trying to add dungeons to a map crashes out with a TypeError.
I'm running on Windows 8.1, MCDungeon 0.14.1, with Minecraft 1.8.1. No mods; completely vanilla.
One dungeon generates fine. When I re-run, the same error occurs in the same place.
I've got minor modifications to my dafault.cfg. 
I read somewhere about a bug that had to do with secret rooms. So I set secret_rooms to 5, but it didn't make any difference, so I set it back.
I re-ran with --debug, but there didn't seem to be any extra info. 
The map is rather large and sprawling. I can provide it if you want, but it's a 200Meg RAR file.
Pastebin of console: http://pastebin.com/d9NadWaS
Pastebin of default.cfg: http://pastebin.com/deK5gnqJ

Let me know if I can provide any more information.

**Comment by JiFish** [comment]
You've got a small mix-up in your command line params, optional params (like offset in this case) need to be specified before the save directory. Try this instead:

```
mcdungeon.exe add -o -2 4 7 TNDungeon 4-8 4-8 2-5 -n -1
```

We probably need some sanity checking on that input.

**Comment by jjaquinta** [comment]
Sadly, that doesn't fix it. New console log here:
http://pastebin.com/DYtmYyF6

So when you say -n overrides -o, does that mean -n goes over the whole map and doesn't pay attention to min_dist/max_dist? What I thought I was doing was filling an annulus sized space around the main area of operation. Ideally I'd like to fill the whole world outside a specific central region.
I removed the -o flag and it got up to dungeon #3, but crashed out with the same error there.

**Comment by JiFish** [comment]
-o is for setting the location of a single dungeon. It has no effect when generating multiple dungeons. min and max width work as you described. No problem there.

I will try to take another look at this at the weekend.

**Comment by jjaquinta** [comment]
Let me know if I can help. I was working on a Forge plugin to scatter and age ruins of different archaeological types (see picture below), but got fed up with them always being a year behind the current version. I also had fun modifying nethack back in the day, so I has some familiarity with what you are doing. If you point me at source I'll look at it, but I haven't worked in python in years.
![10462438_10203099120012750_3933379174388242894_n](https://cloud.githubusercontent.com/assets/1252444/5680677/8886058a-97de-11e4-87ed-7f6d16e6aa18.jpg)

**Comment by orphu** [comment]
Source is right over here --> https://github.com/orphu/mcdungeon/commits/development

;)
