### ISSUE TITLE
regenerate --all and --html

### ISSUE THREAD

**Issue by MikeyCarter** [orphu/mcdungeon#277]
So any way of making this work on the html output?

  python mcdungeon.py regenerate --all -c default.cfg --html Asgard --force Asgard

I'd prefer it if the html output with a base name of the dungeon's name, and/or base co-ordinates.

**Comment by orphu** [comment]
Yeah, that should be doable.

**Comment by MikeyCarter** [comment]
Was playing around with the dungeon.py... basically this is what I'm looking for. 

    def outputhtml(self):
        '''Print all levels of the dungeon block buffer to html.
        We "look-through" any air blocks to blocks underneath'''
        #basename = self.args.html
        d_name_str = self.dungeon_name
        basename = d_name_str.replace(" ", "_")
        force = self.args.force

But I'm sure you guys will have some option for it rather than my hard coding. :smile:

**Comment by orphu** [comment]
Yeah, thanks! I think this will be pretty straight forward.

**Comment by orphu** [comment]
Looking at this one.
