### ISSUE TITLE
Typo in configs & items list

### ISSUE THREAD

**Issue by denemanow** [orphu/mcdungeon#279]
After looking at example config and easy_mode.cfg I've found a few typos.
*Music disc chrip* -> *Music disc chirp*
It's a bit confusing.

**Comment by denemanow** [comment]
Sent pull requests, sorry for doing so *messy* way.

**Comment by orphu** [comment]
Hi there! I only accept pull requests against the development branch. Can you resubmit these?

**Comment by denemanow** [comment]
I will resubmit it as one single pull request along with few other fixes.

**Comment by orphu** [comment]
I found a couple more in the shops configs and corrected them. Closing. Thanks for the pull!
