### ISSUE TITLE
Strange map generation

### ISSUE THREAD

**Issue by denemanow** [orphu/mcdungeon#287]
After regeneration of a dungeon (I cleared my inventory previously) I haven't found a map for first level, but it was present for second level in a chest on level 1.
I've tried to regenerate dungeon without deleting second level map from my inventory, and then I've found only second level map, so I've got two same maps. *And again no first level map.*
Config: **easy_mode**
Branch: **master**

**Comment by denemanow** [comment]
Tried development branch, all the same.

**Comment by orphu** [comment]
Level one maps typically appear in level zero chests. Have you checked there?

**Comment by denemanow** [comment]
Yes, I have.

**Comment by denemanow** [comment]
Map of second level regenerated and have been placed in chest on first level.
Map of first level usually appear in chests placed in entrances - but I haven't found map there.

**Comment by denemanow** [comment]
Possible a bug?

**Comment by orphu** [comment]
Okay, yeah this is a problem with map regeneration. The surface chests aren't in the chest inventory when placed items are distributed, and maps can only be places at their level-1 or above. 

Perhaps the easiest way to deal with this is to allow maps to be place at their level. You'll still never see anything at the surface, but nothing at the surface gets touched on regeneration anyway.
