### ISSUE TITLE
Structure generation method (discussion)

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#293]
Over my last couple of months of absence, I've been teaching ymself Java by working on a Minecraft Forge module to allow generation (and copying and saving) structures in-game.  Grab a copy [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2326830-builders-helper-mod-v2-3-2-copy-paste-save-load) if you want, MC1.7.10 or MC1.8.

The reason I mention it here is that this module grew out of my experiences in procedural generation gleaned form this project, plus the awkwardness of defining a structure to generate in code.  I wanted a separate 'blueprint' language to use to define structures that I could then place in-world easily.

The module that came out of this allows just that.  I can click on an area, and save it to a blueprint file.  I can click on another area, and build a structure (including tile entities, mobs, etc) from a blueprint file.  I can manually define a blueprint, and it can contain procedural-generation randomisation, tests and so on.  The generator take care of the awkward block rotation and so on.  I've even made a (much simplified) dungeon generator.

I am wondering if it would be possible to leverage this to help make new structures in MCDungeon -- either landmarks or rooms.  While it is unlikely to be worth converting the entire Blueprint parser (written in Java) into a PHP subroutine for use by MCDungeon, it might be possible to write a converter that can take a blueprint file (generated by doing a copy-and-save in-game with a couple of clicks) and then spit out an MCDungeon subroutine in PHP to build it.  Being able to build the structure manually in-game and see it is much easier than doing so directly in code (though the latter definitely results in more efficient code).

If it is possible to use this to speed up definition of new structures, it might help to more rapidly increase the richness of the structures created by MCDungeon, and also help cut down on the test/fix/test cycles required for new rooms and structures.

Any thoughts?

**Comment by JiFish** [comment]
I am assuming where you say PHP you mean Python.

The MCEdit project, which also uses pymclevel, can import and place minecraft schematics files. Perhaps that code would suit these needs?

The downside to this approach, I guess, is that schematics are fixed. I wonder how much could actually be moved to them.

**Comment by orphu** [comment]
I've often thought about this type of thing. It can be a lot of work to make something complex since you essentially have to script the whole thing. 

It would be easier to create fixed assets, but it would be harder to build things that adapt or have much variation. Not sure how things like the meta materials would work, or how floor types or features would know the shape of a room.

**Comment by sshipway** [comment]
(Err, yes, Python.  All languages starting with 'P' are the same...  too many diffierent programming languages in my head to keep organised...)

I've not heard of Minecraft Schematics files.  Do you have a link to a spec of this format?  I'd like to be able to add support for it in my mod, at least.

The Blueprint format, at least, supports meta materials (varying randomly and/or by biome), and can include randomness and variation.  Ruins template can also manage metamaterials (varying randomly) though they are more limited in random structure options.  Both have a measure of ability to test for existing content and change behaviour appropriately.

If there were some way to at least leverage this to convert a static blueprint into code, it would still be less work to subsequently add adapting and varying structures... if nothing else, it would save time on the static elements of a room/landmark and just leave the custom elements to be done by hand.

**Comment by orphu** [comment]
Oh, interesting. Do you have a link to the blueprint spec?

**Comment by sshipway** [comment]
The blueprint spec is mine, but I've not documented it in as much detail is I should.  Primarily, the documentation is held in the readme.cfg in the bp/ directory in the module package, along with many examples. Get the zip file [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2326830-builders-helper-mod-v2-4-copy-paste-save-load-mobs) and look in bp/readme.cfg and README.txt.  The bp/tower.cfg holds the config for a procedurally-generated random tower with contents; bp/z_dungeon.cfg is a dungeon generator (not many room types though).

**Comment by JiFish** [comment]
Here's the detail on the schematic format. There are quite a few schematics out there already. http://minecraft.gamepedia.com/Schematic But again, the format is just for static structures.

**Comment by sshipway** [comment]
Thanks for this -- I have now added support for the .schematic file format to my mod, so now I can convert between this and Blueprint format.  Of course, schematic format is pretty limited when compared to Templates and Blueprints, but that makes it easier to convert...

**Comment by kitokofox** [comment]
I was directed here, and I had the idea of being able to have rooms that generate under specific biomes, so you could have (for example) an icy cold slippery dungeon theme in a taiga plains, and maybe a tomb-like generation for a desert.

**Comment by JiFish** [comment]
That's a good idea @kitokofox, but please don't comment on closed issues unless the comment directly pertains to the issue. Feel free to post a new issue.
