### ISSUE TITLE
Make max_dist setting have more helpful defaults

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#294]
Some users have problems initially using MCDungeon because they do not realise the significance of the max_dist setting and that chunks need to be pre-generated in-game.

I suggest having a default setting for max_dist of '-1', to mean 'every chunk in the world'.  This would allow the code to set it dynamically based on the furthest chunk that is already generated, so that users do not need to adjust this setting as their world grows.  Currently it needs to be set properly in the default.cfg before first run.

In addition, if there are very few valid chunks in the world (because someone just generated a new world and never flew about it to pregenerate the chunks) then dungeon generation will likely fail.  A warning message should be output if the world size is very small, or if there are very few available chunks, letting them know that they need to either increae max_dist or cause some chunk generation before running mcdungeon.

**Comment by orphu** [comment]
Of course setting this default to ALL chunks will mean maps that are of any significant size will take a very very long time to do anything on the first run. The cache will be huge. I think this would be a bad experience for anyone not just using a fresh map. 

I still think this just needs to be a reasonable default value. Not too big, or the slowness and ballooning of disk space will upset people. Not too small, or nothing will happen. It already prints out a pretty detailed message:

```
Searching for a suitable location...
Unable to place any more dungeons.
No dungeons were generated!
You may have requested too deep or too large a dungeon, or your
allowed spawn region is too small. If using fill_caves, remember
to add 10 chunks in each direction to the size of your dungeon.
Check min_dist, max_dist, and fill_caves settings in your config.
```

**Comment by sshipway** [comment]
Good point for the huge worlds, though people with a world that size might already be aware and less likely to be caught out.

I think that MCDungeon should check the actual size of the existing world, and at least give an additional warning if this is very small, or if it is significantly less than max_dist (indicating they didnt know that chunks need to be generated already).  Maybe a warning and pause for confirmation if max_dist is exceptionally large, or if the world size is smaller than max_dist?

The detailed message is pretty clear, but it doesn't mention that they may have a big enough max_dist, but there are not yet enough chunks generated in the world.

**Comment by JiFish** [comment]
A warning if your world size is massively incongruous with your max_dist setting would seem to be very useful. But I think there is only so much we can do here.
