### ISSUE TITLE
"Fixed in Dev" label

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#300]
How do you feel about a "Fixed in Dev" label? For issues that are awaiting a release.

**Comment by orphu** [comment]
Well, one thing I've noticed is that if you used a "fixes" or "closes" tag in your commit it will automatically close the issue once I merge to master. A "fixed in dev" label might be redundant since you can see the fixed commits in the issue itself. 

But, if you want to add it go ahead. :)

**Comment by JiFish** [comment]
I did not know that! Shame I can't retroactively add it to my commits. I will just have to remember for the future.
