### ISSUE TITLE
Create wg regions to allow players to claim dungeons.

### ISSUE THREAD

**Issue by PsychoNavigator** [orphu/mcdungeon#301]
I have a world set up in multiverse specifically for dungeon hunting. To prevent players from just bashing straight down to the bottom floor and bypassing challenges, I have the world protected using /rg f __global__ blockbreak deny.

From that point, the way I've been dealing with letting players raid dungeons is having them notify me once they've tamed the throne rooms then using the following:

//pos1 and //pos2 the opposite corners of the dungeons
//expand vert
/rg d dname player (names the dungeon and gives the player ownership)
/rg f dname -g owners blockbreak allow (gives only the owner the ability to destroy)
/rg f dname greeting Player has already defeated this dungeon. Go away!

Needless to say this is fairly tedious when you've got players on a dungeon frenzy, and as much as I'd like to implement dungeons in my main world, I can't because of the restrictions I need to place to prevent cheating the dungeons.

Is it at all possible to have mcdungeon generate regions with flags to protect the plots and add them to the regions.yml folder for that world?

The player could reach the last room and press a command block that would flag them as the owner of the region and give them the ability to raid the dungeon appropriately without the need for an admin to manually set it.

**Comment by sshipway** [comment]
MCDungeon already keeps track of the existing dungeon sizes and locations, so this info is available.

The regions.yml file sounds like something owned by this particular mod that manages the block breaking.  Do you have a specification for this file format and content?  If so, it should be a fairly easy thing to add a new function to MCDungeon that spits out a regions.yml file for all existing dungeons -- or amends an existing one -- in much the same way that the -genpoi command was added to spit out a POI file for Minecraft Overviewer.

What is the name of the plugin that provides this feature, and what is its documentation URL?

**Comment by sshipway** [comment]
YAML seems to be WorldGuard 6, which also supports MySQL.  The format is in here:
http://docs.enginehub.org/manual/worldguard/latest/regions/storage/

This looks like an interesting thing to play with.  If nobody else wants to attempt this -- and if I can get worldguard to work on my dev workstation -- I might have a go at coding up a new mcdungeon --genregions function to maintain these.

**Comment by PsychoNavigator** [comment]
The regions.yml file is created by WorldGuard. 

http://dev.bukkit.org/bukkit-plugins/worldguard/

Documentation appears to be located here:

http://docs.enginehub.org/manual/worldguard/latest/

**Comment by JiFish** [comment]
>  If nobody else wants to attempt this -- and if I can get worldguard to work on my dev workstation -- I might have a go at coding up a new mcdungeon --genregions function to maintain these.

Go for it. You might find this of use: http://pyyaml.org/

**Comment by sshipway** [comment]
So, how about this as a design.
- The function will load in any existing regions.yaml file.
- All known dungeons are given a region  named mcd_${dungeon_name} where dungeon_name has all spaces and punctuation converted to underscores (this may result in some odd region names)  Alternatively, dungeons are named mcd_${dungeon_number}?
- The function creates any as-yet-unknown regions, with empty flags/owners/members and type cuboid, y=0-255, priority 4.
- Any regions with a name prefixed mcd_ that do not correspond to a known dungeon are deleted.
- Any other existing regions are left unmodified. 
- How should we handle treasure hunts?  They may result in a large number of tiny separate regions since it seems that a region cannot be a union of multiple cuboids(?)

**Comment by sshipway** [comment]
Horrible difficulty to get a Bukkit server up and running; seems to be a licensing issue between Mojang and the CraftBukkit meaning a DMCA takedown has removed all CraftBukkit downloads.  I f anyone ca provide me with a working (1.8 in preference) CraftBukkit jar then that would help...

**Comment by PsychoNavigator** [comment]
I got you. Give me a few to get it for you.

**Comment by PsychoNavigator** [comment]
Sent you an email with a link to the address on your profile page, I don't see a way to DM on here.

**Comment by JoeFowlerJDi** [comment]
> Horrible difficulty to get a Bukkit server up and running; seems to be a licensing issue between Mojang and the CraftBukkit meaning a DMCA takedown has removed all CraftBukkit downloads.

CraftBukkit is effectively dead. Use Spigot instead. It's compatible with the same plugins: http://www.spigotmc.org/

**Comment by JiFish** [comment]
> Horrible difficulty to get a Bukkit server up and running; seems to be a licensing issue between Mojang and the CraftBukkit meaning a DMCA takedown has removed all CraftBukkit downloads.

Bukkit is effectively dead. Use spigot instead. It uses the same plugins. http://www.spigotmc.org/

**Comment by sshipway** [comment]
Thanks for the download.  I've tried compiling Spigot but it didn't want to cooperate... anyhow, this should give me a working Bukkit server so I can get the test environment up.  I'll see how time pans out, but if the PyYAML library works out, it shouldn't take too long to get something together.

**Comment by sshipway** [comment]
I have a working WorldGuard server now, so I can start coding something up...

Seems that the WG yaml is stored in `plugins/WorldGuard/worlds/$name/regions.yml` under the same dir as the world data dir and has a documented YAML structure.

On a related note, the WorldBorder Bukkit plugin is amazing -- you can set it to autogenerate the world ready to have MCDungeons added using just a couple of commands.

**Comment by PsychoNavigator** [comment]
Yes, I love worldborder so much. Makes life so much easier as a server owner!

**Comment by sshipway** [comment]
I have a working set of code in https://github.com/sshipway/mcdungeon/tree/wbregions that adds the `genregions --regionfile regions.yml` command to MCDungeon.

It names the new regions according to sanitised dungeon names, prefixed by `MDC_`.  Any existing regions with the `MCD_` prefix are preserved, unless they do not correspond to an existing dungeon, in which case they are deleted.  Other regions are preserved.  The `expand` setting is ignored for region size.  Regions are created Y=0-255, flags/members/owners as default.

This seems to work with my test setup, but as I am unfamiliar with WorldGuard I suspect it needs a bit more thorough testing before I create a pull request.  @PsychoNavigator - are you able to pull this from my fork and test it our on your setup (take a backup of your regions.yml first!) to verify it is compatible with Bukkit/WorldGuard?

**Comment by PsychoNavigator** [comment]
I'd be happy to try! Do I just download the zip and install it to a directory?

**Comment by sshipway** [comment]
Might be a bit complex, as you need to install Python, numpy, PyYaml, and then the application directory before running the mcdungeon.py (the only file actually changed).  If you're not familiar with this sort of thing it might be awkward.  I'll see if I can work out how to compile to a binary that I can pass on.

**Comment by PsychoNavigator** [comment]
That would be good, thank you. I'll be happy to install and run it. I have spare pre-rendered world ready to test with.

**Comment by sshipway** [comment]
I've found the install builder, and managed to make it run.  
You should be able to pick up a Windows binary install package from https://webdropoff.auckland.ac.nz/cgi-bin/pickup/40cb27ff1cd0f6da1d5d1ae47a09c887/230945 for the next 7 days.  Not sure if this is a 32bit or 64bit installer - it claims to be 64bit but I have 32bit Python installed ...
If you can make it work please let me know.

**Comment by PsychoNavigator** [comment]
Ahh... I'm using a linux server, you sure I can't run anything from my end to compile?

**Comment by sshipway** [comment]
I will try and work out how to do this.  With luck, the PyInstaller script will work under Linux as well without modification...

**Comment by sshipway** [comment]
If you are using Linux, then presumably you are running from the .py files; in which case you should be able to download the wbregions branch from https://github.com/sshipway/mcdungeon/wbregions and install it directly.  The only file to have changed is the mcdungeon.py so you could just download that and replace it.

**Comment by sshipway** [comment]
Pull request #302 

Tested using Spigot 1.8, WorldEdit 6.0, WorldGuard 5.9 and WorldGuard 6.0 beta 5 under Windows, regions saved and loaded without corruption.

**Comment by PsychoNavigator** [comment]
Nice. I haven't gotten to test this yet. I did try copying the files directly in and running it a say ago but it made a fuss about not being able to find a specific file in the folder.

Surely was doing it wrong.

Since you have it working, how is it implemented currently? Could I specify custom flags in the setup, and how does a player take ownership of a dungeon, or would that be the next logical step?

**Comment by sshipway** [comment]
(Sorry for slow response, been busy in work this last week)
I have implemented this by allowing you to call mcdungeon with a '--genregions' flag, combined with a world identifier, and the location of the regions.yml file.  
- MCdungeon will read in any existing regions.yml, and will assume that any regions starting 'mcd_' are generated by itself.  All others will be preserved.  
- Any mcd_ regions that do not correspond to a current dungeon in the world will be removed
- Any dungeons that do not have a corresponding region will have one created, with empty flags etc and default level 4.
- Existing mcd_ regions with a corresponding dungeon will be preserved as-is, so any subsequent changes are preserved.
- There is no way to specify the default values the new regions are created with.  Possibly I could make it search for a region called 'mcd_DEFAULT' and use the settings here if one exists?  This might be a useful improvement.
- Regions are named mcd_ followed by the dungeon name, with spaces mapped to _ and all punctuation removed, and mapped to lowercase.

**Comment by sshipway** [comment]
@PsychoNavigator - if you can download the updated mcdungeon.py from my fork, you should be able to run it on your server as a replacement for your existing (if you have the latest version).  If it fails, let me know the error message (you might not have the pyyaml library?).
To run, just use `python mcdungeon.py genregions --regionfile /path/to/my/regions.yml  /path/to/my/world`

**Comment by sshipway** [comment]
I have added the ability to set the default options for a newly-created region -- they are pulled from the global region `__mcd_default__`  if it exists (this is separate from the `__global__` region of course).

I have tested this on my local Windows-based test Bukkit setup, with a bunch of old and newly-generated MCDungeons, but I would really like it to be tested by someone else as I'm not fully familiar with Bukkit.

What needs to be done to create a Linux distribution package from my fork?  I've managed to create a Windows binary but of course this is no use for PsychoNavigator to test under Linux.

Documentation to come... but it won't need to be very complex.

**Comment by orphu** [comment]
Well, I stopped making a binary for Linux because no one downloaded it and it was pointless. 

If you have Linux, run the python version. If you have Python 2.7, you only need numpy, and there is almost certainly a package for it in your distro. Pyaml is not required, since McDungeon already ships with it. 

@PsychoNavigator : what is your distro? For example. with Ubuntu, python 2.7 is already installed. Just install numpy:

```sudo apt-get install python-numpy```

**Comment by PsychoNavigator** [comment]
Okay, will do in the next 24. Thank you guys and I will follow up with feedback on this.

**Comment by orphu** [comment]
Just go to @sshipway 's repo:

https://github.com/sshipway/mcdungeon/tree/wbregions

Click the "Download ZIP" button there. Unzip the contents somewhere and use it from within that directory. If you gave Python 2.7+numpy installed it should just work. 

More info here:

http://mcdungeon-docs.bubblemod.org/en/latest/downloading-running/#basic-command-line-use

**Comment by sshipway** [comment]
For the new `genregions` command, use something like:
`./mcdungeon.py genregions --regionfile /path/to/my/regions.yml /path/to/my/world`
If the `regions.yml` does not exist, it will be created.  If it does exist, make a backup first!  If your Bukkit server is running, you'll need to call `/rg load` to reload the updated file after changes.
You can also call this via the interactive menu if you really want to.
The newly generated `regions.yml` will have all the old comments removed, and new comments indicating it was generated by MCDungeon and telling you about the `__mcd_default__` global region.

**Comment by sshipway** [comment]
On a related note, I notice that the second part of your request was to have a button in the final treasure room that could be pressed to trigger a command block and run the WorldGuard commands necessary to allocate the region to that player, and protect it from everyone else.
That would be a little more complex, as it would need to be done at the dungeon generation step, and it would be difficult to work out where this button should be located.
You might still need to manually allocate the region to the player, but at least the most awkward bit - defining the region itself - will already be done.

**Comment by PsychoNavigator** [comment]
Cheers, will give it a shot and report back.

**Comment by PsychoNavigator** [comment]
Okay, made a new directory for this version of McD, and tried to run it.

user@server:~/lab/mcd/mcdWG$ ./mcdungeon.py interactive
Traceback (most recent call last):
  File "./mcdungeon.py", line 15, in <module>
    from pymclevel import mclevel
ImportError: No module named pymclevel

**Comment by sshipway** [comment]
Ah -- pymclevel is a subproject, isn't it?  You need to copy the pymclevel directory and contents from your other install (or else download from https://github.com/orphu/pymclevel/tree/d5abd5dea415a16b53e6f6d5116ef65ef10d433e ).  This happens automatically if you do a git clone...
`git clone --recursive --branch development https://sshipway@github.com/sshipway/mcdungeon`

Sorry, I'd forgotten that a zip download is not recursive.

**Comment by PsychoNavigator** [comment]
Alright, I've gotten the script to generate dungeons, but am stalling out when trying to gen a regions file.

user@server:~/lab/mcd/mcdungeon$ ./mcdungeon.py genregions --regionfile /user/McMyAdmin/Minecraft/plugins/WorldGuard/worlds/dw2/regions.yml /user/McMyAdmin/Minecraft/dw2
MCDungeon 0.14.3
usage: mcdungeon.py [-h] [-v] [-q]
                    {interactive,addth,add,list,genpoi,delete,regenerate} ...
mcdungeon.py: error: invalid choice: 'genregions' (choose from 'interactive', 'addth', 'add', 'list', 'genpoi', 'delete', 'regenerate')
admin@consortium:~/lab/mcd/mcdungeon$

**Comment by JiFish** [comment]
Sounds like you have either grabbed or are using the wrong version. You want sshipway's wbregions fork from here: https://github.com/sshipway/mcdungeon/tree/wbregions

**Comment by PsychoNavigator** [comment]
I'm confused as to how that happened when I did a git clone using the link sshipway provided.

I am not a smart man.

**Comment by JiFish** [comment]
Ah, I see there's a mistake in that clone. It's fetching the wrong branch. Try this:

git clone --recursive --branch wbregions https://sshipway@github.com/sshipway/mcdungeon

**Comment by PsychoNavigator** [comment]
Alright, that definitely sorted out my issue with the genregions thing not being an option.

Now I'm at another stumbling block.

user@server:~/lab/mcdWG/mcdungeon$ ./mcdungeon.py genregions --regionfile /user/McMyAdmin/Minecraft/plugins/WorldGuard/worlds/dw2/regions.yml /user/McMyAdmin/Minecraft/dw2
MCDungeon 0.14.3
Loaded 374 materials.
Loaded 698 items.
Loaded 58 items from NBT files.
Trying to open: /user/McMyAdmin/Minecraft/dw2
Trying to open: /user/McMyAdmin/Minecraft/dw2
Failed to open world: /user/McMyAdmin/Minecraft/dw2
user@server:~/lab/mcdWG/mcdungeon$

**Comment by JiFish** [comment]
Is the path to your save definitely correct? You shouldn't get that error unless MCDungeon cannot find the world directory.

**Comment by PsychoNavigator** [comment]
Yes that was precisely it.

./mcdungeon.py genregions --regionfile ~/McMyAdmin/Minecraft/plugins/WorldGuard/worlds/dw2/regions.yml ~/McMyAdmin/Minecraft/dw2

This fixed it. I was adding in the user's home directory the wrong way. Thank you. It's generating now.

**Comment by PsychoNavigator** [comment]
Okay world loaded, server restarted and the regions are all there. This is amazing.

Now here's a question for sshipway. There are no flags on any of the regions. Would there be a way to manually configure a file so that it generates all regions with a specified set of flags?

To suit all cases, one set would be needed for __global__ and another for all with mcd_ prefixes.

Possible at all to have a config for this?

**Comment by sshipway** [comment]
Glad to hear its working.  Sorry for putting the wrong branch in the clone command above, I had quickly copied it from another script...

If you create a new global region called `__mcd_default__` then the settings of this region will be used to define any new regions.  So, set the flags you want against this default global region, delete and recreate all the `mcd_` regions, and they will be initially created as per the `__mcd_default__` region settings.

**Comment by PsychoNavigator** [comment]
Amazing. Thank you. Just about to go to bed, will be trying this in the morning. This is rad. Really hope to see this added into the main builds.

**Comment by orphu** [comment]
I was waiting for some feedback on bugs. Would be nice if @sshipway could update the docs with his new feature as well. :) 

https://github.com/orphu/mcdungeon-docs

**Comment by sshipway** [comment]
Yeah, OK.  If no changes and/or improvements to this patch come to mind, then  I'll document the genregions function as it is now into a fork of the mcdungeon-docs repo this coming week.

**Comment by sshipway** [comment]
... documentation created.

**Comment by PsychoNavigator** [comment]
I still need to test setting up the default flags and whatnot. 

The only real issue that I see is the length/complexity of the names for the regions. Would it be possible to refer to them by a numbering system such as mcd_0, mcd_1, etc?

**Comment by sshipway** [comment]
If they were given numbers, there would be no way to reliably tie existing regions back to MCDungeons when running a second time.  The only unique identifier in the MCD cache is the name and the coordinates (and a 9-digit number would be just as awkward).

You can define the `__mcd_default__` global region (note the double underscore prefix/suffix!) either directly in the yml file or in-game, it doesn't matter.  It just has to exist at the point when the genregions is executed, since it is copied to make the new regions.

**Comment by sshipway** [comment]
This can be closed now as it was fixed by pull request #302
