### ISSUE TITLE
Button falls off the wall in construction rooms

### ISSUE THREAD

**Issue by MikeyCarter** [orphu/mcdungeon#303]
I've hit this a few times.  If the secret room is in a "construction zone" the button can be on a fence sticking in the middle of the air.   

If you then press the button... it just falls to the floor.   Any way of making sure that if a button is placed there's an actually block behind it.

Next time I run into it I'll take a screen shot.

**Comment by orphu** [comment]
I've seen this too. Should be an easy fix.

**Comment by JiFish** [comment]
Yes. This is due to some of the wall materials in this room type do not allow buttons to be placed on them. (Fences, I suspect.)

Suggest that the block behind the button should be replace with smoothstone if it's currently a fence.

**Comment by orphu** [comment]
Didn't quite fix this. It also happens with portcullises.
