### ISSUE TITLE
File directories

### ISSUE THREAD

**Issue by AmbassadorPineapple** [orphu/mcdungeon#304]
I like to use this program to modify my worlds at school. Somebody in years past put the minecraft files in a shared folder, and everyone can use it. The issue I'm pointing at is that MCdungeon always searches in the .appdata folder, and I can't edit worlds in there. Please add a directory modification feature. It would be a great thing.

**Comment by JiFish** [comment]
This feature already exists. Use the --dir command line option to specify the map folder. See http://mcdungeon-docs.bubblemod.org/en/latest/command-line-ref/#cmdoption--dir

**Comment by AmbassadorPineapple** [comment]
Where do I do this?

**Comment by AmbassadorPineapple** [comment]
Input the command, I mean?

**Comment by JiFish** [comment]
I am assuming you are using windows and are not familiar with using the command-line. In which case, this should do what you want:

* Make a copy of launcher.bat. Call it something like launcher_alternate.bat
* Edit your new file in a text editor, e.g. notepad
* Change this line: ```mcdungeon interactive```
* to this: ```mcdungeon interactive --dir [path to your folder]```
* For example, ```mcdungeon interactive c:\some\folder```
* Save the file and double-click it

**Comment by AmbassadorPineapple** [comment]
Thank you. I'll leave this open for a day or two, just in case I have questions.

**Comment by AmbassadorPineapple** [comment]
I just thought of something: do I have to path it to the save folder as well?

**Comment by AmbassadorPineapple** [comment]
Never mind, I figured that last one out on my own.

**Comment by AmbassadorPineapple** [comment]
Thanks JiFish!

**Comment by JiFish** [comment]
No problem.
