### ISSUE TITLE
Way of Including/Overriding Config files

### ISSUE THREAD

**Issue by MikeyCarter** [orphu/mcdungeon#306]
When you release new versions some times you update the config files.   That means the various config files I've been tweaking also need to be updated.

Would be useful if I could have a config file which overrides a few entries then includes the "default.cfg".

So the file might look like:

includes: "default-maze.cfg"
secret_rooms: 15
fill_caves: true

sort of thing.

**Comment by JiFish** [comment]
I have looked at this but decided against it as program currently stands. The way the configuration file is loaded currently is not ideal for inheritance. While it possibly could be made to work, it would be a kludge to say the least.

If anyone really wants to attempt this, I'd suggest ripping out the entirety of the configuration loading code and replacing it with something like ConfigObj. (or some other python library suitable for the purpose.) Which would also allow for better packaging for configurations. See issue #164 for my and orphu's notes on this.
