### ISSUE TITLE
Make NBT changes for 1.9

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#308]
See https://www.reddit.com/r/Minecraft/comments/3f102e/snapshot_15w31a/ctkb0ow

Likely the only place this need be changed is in the spawner nbt files.

Also, it's pretty likely the old tags will continue to work for back-compatibility, but I have not tested.

**Comment by JiFish** [comment]
The guards in the armoury secret room type also need to be updated.

**Comment by JiFish** [comment]
In fact the old tags will NOT work in the old version: https://bugs.mojang.com/browse/MC-85544 So this will have to be changed.

**Comment by orphu** [comment]
Changing this to broadly apply to all documented NBT changes. I'll start with the NBT helpers in utils.py and work from there. This should cover many cases. 

Changes summarized nicely here:

http://www.minecraftforum.net/forums/minecraft-discussion/redstone-discussion-and/command-blocks/2488148-1-9-nbt-changes-and-additions#TileAllCommandBlocks

**Comment by orphu** [comment]
Noting that item frames are broken. 

Items and the frames end up on the floor as a free item detached from the wall. Not sure if this is an NBT issue or what.

**Comment by orphu** [comment]
I think this is basically done.
