### ISSUE TITLE
Change items.txt to use string IDs instead of numeric

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#314]
Change items.txt to use string IDs instead of numeric. Will allow #311 to work, and is also needed to allow new 1.9 loot e.g. Chorus Fruit.

Edit: materials.cfg will also have to be extended to provide a string ID in addition to the current numeric ID.

**Comment by JiFish** [comment]
Since the materials change, the byID function is never used. That will make this job easier.

**Comment by JiFish** [comment]
Okay, I've added string IDs to items.txt and materials.cfg and I've also altered items.py and materials.py to fetch them. I'll have something to commit for the weekend.

**Comment by JiFish** [comment]
This commit makes MCDungeon use string IDs for items, in most cases. Some numeric IDs remain where they have been hard-coded. Since these are all old items this should be OK. However, I would like to remove these eventually too.

There might be some impact on written book formatting, I'm not sure if the old formatting will work using the new ID. I will have to check that out before I switch that one.

**Comment by JiFish** [comment]
Oh, this also makes the changes from issue #311 work correctly in the current snapshot.

**Comment by orphu** [comment]
Commit 1d6a8c4 is related.
