### ISSUE TITLE
Potion traps broken in 1.9 snapshots

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#315]
Potion traps broken in 1.9 snapshots. Looks like they need to be switched over to the new tags. Potions now use the potion tag instead of a damage value e.g. {Potion:"minecraft:strength"} See also issue #311 
![broken_trap](https://cloud.githubusercontent.com/assets/1314002/9232615/9aec4fda-4126-11e5-93f7-4be3a7e414bd.jpg)

**Comment by orphu** [comment]
The [projectile traps] section will need to be changed. Might be better to just reference a predefined item instead of the way it currently works.

**Comment by JiFish** [comment]
What we really need is a function that can turn a NBT object in to it's JSON equivalent. That way the existing item building stuff can be used.

**Comment by orphu** [comment]
Turns out this can be corrected by tweaking the config files!
