### ISSUE TITLE
Mobs not generating in snapshots unless map is loaded in 1.8 first

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#318]
Mobs not generating unless map is loaded in 1.8 first. Tested this with the shopkeeper villagers and the secret armory guard.

If the map is loaded straight in to a snapshot, they will not appear. If the chunk has been passed through 1.8, however, the mob then will appear in the snapshot.

1.8 must be making some changes to the mob's tag. Suggest we figure out what that is.

Edit: To clarify this is mob entities, not mob spawner blocks.

I've ruled out #308 as a potential cause for this by eliminating the inventory tags and retesting.

**Comment by JiFish** [comment]
This is a really weird one.

"XXX of Person" signs are broken the snapshot, but "Person's XXX" signs are not?! Again, unless passed through 1.8 first.

**Comment by JiFish** [comment]
May require verifying in most recent snapshot.

**Comment by orphu** [comment]
I've confirmed that placed mobs (villagers, death knights, witches, etc) do not appear in 1.9 release.

**Comment by sshipway** [comment]
Hmm, clearly it's going to be some 1.7-format NBT that is supported and migrated by 1.8 but not supported by 1.9.  
The way I debugged some of this before way to use my Builder's Helper Forge mod to copy and save the tags of blocks and mob.  Under 1.8, load the world, and use the BH wand to select an area contaiing the mob or block.  Then save this to a file and you can see the NBT of the mob; I used this to see what NBT tags were needed.  I'm not sure which you are generating; some of the tags changed type as well I think

This is a valid partial mob NBT under 1.8
>
{DropChances:[0:0.5f,1:0.5f,2:0.5f,3:0.5f,4:0.5f,],PersistenceRequired:1b,HealF:20.0f,id:"Zombie",ConversionTime:-1,Health:20s,OnGround:1b,CustomName:"Pirate",Equipment:[0:{id:"minecraft:iron_sword",Count:1b,Damage:0s,},1:{},2:{id:"minecraft:leather_leggings",Count:1b,Damage:0s,tag:{display:{color:0,},},},3:{id:"minecraft:leather_chestplate",Count:1b,Damage:0s,tag:{display:{color:16711680,},},},4:{id:"minecraft:leather_helmet",Count:1b,Damage:0s,tag:{display:{color:255,},Unbreakable:1b,},},],CanPickUpLoot:1b,CustomNameVisible:0b,}

**Comment by orphu** [comment]
For spawners, the issue is that the EntityId is gone now and replaced by SpawPotentials. 

See: 

http://minecraft.gamepedia.com/Monster_Spawner

**Comment by sshipway** [comment]
Villagers now need a career and a profession.  This might be why they are missing?
I'll fire up the BH mod under 1.8 again and get a full mob NBT dump to see if I can spot what is needed.  Will post it here if problem is not yet solved

**Comment by orphu** [comment]
Will revisit this after #308

**Comment by orphu** [comment]
I think this is fixed. Signs, villagers, and guards in armories appear to work now.
