### ISSUE TITLE
Chest tile entity in incorrect location

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#321]
I've noticed this when loading a freshly dungeoned world on a Bukkit 1.8 server, with dungeons created with MCD 0.14.2

The server reports a warning that a Chest tile entity is in a block that is not a chest.  It goes on to start the server correctly.

When I go to the coordinates of the reported error, it is always within a dungeon, though not at a chest.

I have not been able to identify which (if any) of the dungeon chests is empty (indicating it is the one with the misplaced tile entity).  Also I cannot cause this at will - not every dungeon seems to result in this problem.

One strong possibility is that the dungeon was built over the top of a hidden cache, or a mineshaft.  These contain chests, and if the tile entity was not deleted when the block was replaced, it would result in this behaviour.  Maybe the MCD block setting call should also check for any tile entities and remove them?

**Comment by orphu** [comment]
MCD does take care to remove existing tile entities, but I think sometimes the game places a few after a chunk is loaded. Especially near the edge.

**Comment by Catreina** [comment]
In my test map (500x500) there were 28 dungeons placed, and I believe 9 of these issues on first run, and 4 on the second run.  Minecraft did seem to repair the missing ones on the runs... probably after chunk loading (as opposed to initial generation)

**Comment by orphu** [comment]
I believe this may be fixed by 7f1a099430ab8b931b95247124ab6d454f966735

**Comment by orphu** [comment]
I have to back this out a little for map chunks built prior to 1.9. Incomplete chunks won't always be detected if you're using a map generated with MC prior to 1.9.

**Comment by Catreina** [comment]
I will try to check this when I get a chance. Been super busy developing
this server and what not.

**Comment by JiFish** [comment]
Closing this as very old and hopefully fixed.
