### ISSUE TITLE
v0.15 release milestone.

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#323]
Mojang are wrapping up on features and switching to bug-fixing soon. @orphu were you hoping to do a release to coincide with 1.9?

Even if that's not the case. (There's still a couple of feature-breaking bugs introduced by the 1.9 snapshots.) It would be nice to have a v0.15 milestone so we can group together the issues that need addressing.

**Comment by orphu** [comment]
Sounds good. I set an arbitrary date on Nov. 30.

**Comment by orphu** [comment]
So, is there an expected release date for 1.9?

**Comment by JiFish** [comment]
No expected release date yet. But they have said they are done adding features and from here to the 1.9 release it will just be balancing and bug fixes.

So, sounds like soon. But who knows.

**Comment by orphu** [comment]
1.9 is out. Looks like there are a few issues reported.

Hopefully I can find some time to do a little testing.

**Comment by sshipway** [comment]
I think it will be a little time before 1.9 usage picks up, since Forge and Bukkit/Spigot are not yet available for the 1.9 branch and no mods have been ported to it; so there's still time for it to settle down and initial bugs to be detected.

Are there any incompatibilities in the latest 0.15 development that would mean they do not work with 1.8?  IE, any structures that rely on 1.9 features, rather than 1.9-specific treasure items?

**Comment by orphu** [comment]
Yes, I think there are several changes in 0.15 that will break in 1.8.

**Comment by JiFish** [comment]
Hey all,

@orphu great work on the 1.9 compatibility. I'm looking forward to giving this a try with in 1.9 with the new combat mechanics. I'm thinking it's going to be a lot harder. I might need to adjust the difficulty of my config file.

I've unassigned a couple of issues from myself. I've not a lot of time at the second and don't want to hog them. But I'm hoping to get some time to lend a hand soon. If that's the case, I'll have a look at #327.

**Comment by orphu** [comment]
Things are coming along. A lot broke due to all the NBT changes and shift to string IDs. 

I keep finding broken things. Need testers!

**Comment by sshipway** [comment]
... I'll download it and play this weekend.  Our home setup is bukkit-based so still all 1.8 but I should be able to make MCD 0.15 run with 1.8 simply by removing the new objects from the config files, I think.

**Comment by orphu** [comment]
I've fixed all the open issues with 1.9, and things seems to be working pretty well. 

I'll give it another week or so of testing and push out a release if things are still good. Targeting the 27th.

**Comment by sshipway** [comment]
Am currently testing teasure hunt generation under the dev branch and 1.9

**Comment by orphu** [comment]
Hooray! Thanks for the help!
