### ISSUE TITLE
Integration with Bukkit dynmap mod [feature]

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#326]
I've created a Bukkit plugin that exposes the MCdungeon entities via the Dynmap plugin.  This works by reading the Dungeon and Treasure Hunt caches and adding Dynmap markers via the API, so that dungeons can be visible via the Dynmap dynamic map.  This is similar to POIs in Overviewer but a different format.

http://mods.curse.com/bukkit-plugins/minecraft/dynmap-mcdungeon

It would be good to have a link to this mod from the MCDungeon website or in the documentation to let people know the resource is available.

**Comment by orphu** [comment]
Will link on website and docs.
