### ISSUE TITLE
Replace loot generation with NBT loot table generation

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#332]
This is a big job.

Minecraft 1.9 comes with the ability to create custom loot tables. These tables can be applied to specific chests, offering an alternative to MCDungeon's loot generator.

http://minecraft.gamepedia.com/Loot_table

There are a couple of advantages to doing this:
- The new lucky and unlucky effects will alter the contents of the chests when opened
- We can have loot tables for custom mobs
- since loot is generated from a loot file, it will be possible to update your loot without re-generating every chest
- It may obsolete some of our existing code

This would probably also require a re-think of how we define loot tables in the configs. It might even require a sacrifice in features. (For example, our enchanting system is more flexible than theirs. But I am not sure the two could co-exist.)

**Comment by orphu** [comment]
Hm, yeah it's interesting. No other way to tap into luck unless this is done. 

I guess we could generate master loot tables per level. Then some of the customer features (secret rooms, treasure rooms) would need their own tables. 

If the config file is changes, we'd have to detect this, and regenerate all the loot table files though. Adding dungeons later, might affect older dungeons. Unless loot table name spaces are built per dungeon. 

The more I think about it, each dungeon would probably need it's own name space so your could have dungeons built with multiple configs in the same map.

**Comment by sshipway** [comment]
How would this work with items such as maps, flyers, cell codes, holy hand grenade etc that needs to be assigned to chests specifically rather than randomly?  Can you specify certain items to be present, plus a random selection at first open?

**Comment by orphu** [comment]
Not sure if triggering a loot table replaces everything in the chest, or just adds to it. Would need to test that out.

**Comment by JiFish** [comment]
> Not sure if triggering a loot table replaces everything in the chest, or just adds to it.

Actually I think it does neither. But that will need to be checked.

**Comment by ehx-v1** [comment]
Not a friend of this. Still using 1.8 because I use WorldEdit (Forge version) a lot and don't want to go through all the mess of setting up yet another Forge for 1.9 or later. Also, I'm still searching my hard drive for the 1.9 version of my favourite resource pack. Plus, I'm severely unsure if Ruins has been updated to 1.9 or later yet (which stops being a thing if this turns out incompatible with Ruins anyway). So, please hold back with features that break compatibility to 1.8, unless of course you make them optional.

To make it clear, if you really need to introduce features of the newest MineCraft era, I could settle with getting past point 1 and 2. Incompatibility with Ruins, however, is a problem for me, especially if it unneccessarily arises from conflicting version requirements.

**Comment by ehx-v1** [comment]
Whoops, forgot about release separation. Please just forget that I had another comment here.

**Comment by JiFish** [comment]
At this point, I doubt this is going to happen. With the removal of the Luck state, much of the  motivation to do this is gone.

>  So, please hold back with features that break compatibility to 1.8, unless of course you make them optional.

We're not going to do this. MCDungeon only supports the most recent version of Minecraft on it's release. We won't ever be making considerations for older versions. Sorry, but it's simply too much of a burden.

On that note, it is extremely unwise to run MCDungeon with anything other than the version specified in the change log. Minecraft makes internal changes all the time. Most of what changes from update to update is compatibility for the newest versions.

**Comment by JiFish** [comment]
I'm going to go ahead and close this as a feature request. As previously mentioned, there's much less motivation to do this now there's no proper in-game luck effect. Combined with the other issue of maps etc. this just doesn't seem worthwhile.
