### ISSUE TITLE
Portable format in cache files (feature req)

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#333]
The mcdungeon cache files use Pickle format; this is not even compatible between Python versions, and is horribly difficult to read from other languages.

Can we make MCDungeon use a different, standard cache format (YAML?) instead -- migrating old cache format if found, of course?

Obviously this is not so high priority, so after 0.15.0, but it would make integration with other things (dynmap for example) easier.

**Comment by orphu** [comment]
Well, cPickle is very compatible between versions (It's actually guaranteed to be backwards compatible across Python versions) and is cross platform. It's also fairly space efficient and fast.

Are you talking about the chunk cache, the dungeon cache, or the book format? 

I can't see changing the chunk cache format. It would be huge if expanded to a text format. 

However, the dungeon cache is basically a bunch of NBTs anyway. I don't even know why I used pickle. A better way might be to just save out a compressed NBT. There are tons of NBT libraries out there.

**Comment by orphu** [comment]
I think I can just bump the cache version number and that will cause the cache to automatically be regenerated in the new format. No need to support reading old cache versions. 

The only place I'll need to support reading old formats will be in the encode/decode functions for the NBT structures. They currently pickle the key->value pairs for the dungeon configs. The benefit there was not having to deal with reading in the different types and recreating the python objects. Pickle does this automatically. This is limited to strings, ints, and the Vec type in utils.py. So this will need to be manually parsed, but there are helper functions already in utils.py for the Vec. NBT has int and string types that can be leveraged. There is no Vec equivalent. 

Could use a string with the parse functions in utils.py, or store them as lists of doubles like MC does for entities.

**Comment by sshipway** [comment]
I'm mainly talking about the Dungeon (and THunt) cache, as this is the file likely to be read by external entities.  The book format would also be involved since the dungeon cache is basically just a pickled list of book locations and content -- and the content is itself pickled.

While I like YAML, it would seem to be more logical to use an NBT format for the caches.  Then, it would be much easier to include books.  A position Vec iwould map to a Double Array[3] I think (unpickling a Vec is the most difficult bit for non-Python code).

For book pages, which are pickled varname+value pairs, maybe a parseable text format like "SET:varname=type:value" would work, with Vec types being represented by  "pos=vec:1.2,3.4,5.6" or similar.  The load functions could identify if the page is pickled or newformat by looking for the initial 'SET:'; if it is not there, then assume its a pickle.

**Comment by orphu** [comment]
Okay, looking at it a bit more. I still want to store NBTs in the cache since that's what gets used internally. I don't see a lot of sense translating back and forth. 

BUT... I just noticed it would be trivial to dump out a YAML versions as dungeon_cache.yaml and thunt_cache.yaml along side the binary NBT versions, since the pyaml module is included anyway! They aren't that large.

**Comment by sshipway** [comment]
NBT format is no problem to read from other languages; so  the cache could be completely NBT rather than a pickled array of NBT ... It's the pickling that is the issue, not the NBT -- though the pickled pages in the book are still problematic.

Having a parallel YAML dump, though, would be just as good from the point of compatibility.  As long as 3rd party programs can read the dungeon/thunt caches, it doesnt matter if it is a parallel copy!  Maybe we can have this yaml file as holding just the important information rather than entire chest NBT ... so the book pages are already unpacked merged and unpickled.

**Comment by orphu** [comment]
Okay, so now I totally remember why I used pickle. I didn't want to have to deal with creating a dumper/parser for complex nested Python structures and custom classes. pyyaml can't really handle it. 

So, I added a parallel dump, with one hack to deal with one list of Vecs in treasure hunts. Not proud of it.

**Comment by JiFish** [comment]
Since this commit, I've been getting the following error every time. (Default config, interactive mode.)

**Comment by JiFish** [comment]
Since this commit, I've been getting the following error message every time. (Default config, interactive mode.)

```
Relighting chunks: 100%[=============================================>] 0:00:01
Saving...
'int' object is not subscriptable
Failed to write dungeon_scan_version.yaml. Check permissions and try again.
```

Apologies for the mistaken issue close/open.

**Comment by orphu** [comment]
Whoops. Fixed I think. Sorry!

**Comment by JiFish** [comment]
Looking good.
