### ISSUE TITLE
Generating multiple treasure hunts can cause crash 

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#336]
When generating multiple treasure hunts, there is an error on the third item:
````
D:\src\github\mcdungeon>.\mcdungeon.py addth --write -n 3 "Flat World" 1-10 20
````
... lots of output ...
````
***** Placing treasure hunt 2 of 3 *****

Searching for a suitable location...
Treasure hunt steps: 20
Location:  (-80,46,272)
Theme: pirate
Owner: Captain Bellrd
Location:  (-80,46,272)
Generating landmarks...
Creating landmarks: 100%[============================================>] 0:00:02
Placed 20 landmarks.
Treasure hunt name: Captain Bellrd's treasure
Rendering landmarks: 100%[===========================================>] 0:00:00
Placing chests: 100%[================================================>] 0:00:00
Placing spawners: 100%[==============================================>] 0:00:00
Processing biomes: 100%[=============================================>] 0:00:00
Writing block buffer: 100%[==========================================>] 0:00:00
Creating tile entities...
Creating entities...
Marking dirty chunks...
Relighting chunks: 100%[=============================================>] 0:00:09
Saving...
Traceback (most recent call last):
  File "D:\src\github\mcdungeon\mcdungeon.py", line 1747, in <module>
    result = thunt.generate(cache_path, __version__)
  File "D:\src\github\mcdungeon\treasure_hunt.py", line 182, in generate
    self.world.saveInPlace()
  File "D:\src\github\mcdungeon\pymclevel\infiniteworld.py", line 1171, in saveInPlace
    os.mkdir(self.unsavedWorkFolder.filename)
WindowsError: [Error 5] Access is denied: u'C:\\Users\\sshi052\\AppData\\Roaming\\.minecraft\\saves\\Flat World\\##MCEDIT.TEMP##'
````
The MCEDIT.TEMP directory is created and then removed during the process.  Is it possible that something has a file descriptor that has not been closed and so the temp directory cannot be recreated?

**Comment by orphu** [comment]
Seems like it. Do you get the same error making multiple dungeons? 

I'm not able to repro ion OSX or Linux. Will try Windows later.

**Comment by orphu** [comment]
Tried this on Windows this evening, and I'm not able to repro. I tried interactive mode, and also your example command line. 

Any other details that might be unique to your setup? Any chance MCEdit or Minecraft were running?

**Comment by sshipway** [comment]
Well, I don't have MCEdit installed, and Minecraft was definitely not running... however, I've just tried it again  after a reboot, and I can't reproduce it today either.  Maybe there was something windowsy holding an FD open to the directory that broke it; anyway it doesn't happen now, so I think this can probably be closed.
