### ISSUE TITLE
Memorial landmark framed maps and signs broken

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#337]
On the Memorial landmark
- The "in memory of $painting" wallsigns do not display (probably 1.9 sign format)
- The paintings (framed maps) are sometimes placed 1 block to the right from where they should be (this one is odd)

**Comment by sshipway** [comment]
The missing sign is because the metadata was set to 0 which is OK and defaults to N in 1.8 but is invalid and hides the sign in 1.9.  Fixing, pull req shortly.

**Comment by orphu** [comment]
I've noticed the off by one painting thing on paintings with a size of three. I believe this is a separate issue.

**Comment by sshipway** [comment]
I've worked out the off-by-one paintings bug ; this might affect other features and things too.

Under 1.9, the Pos tag for ItemFrames is a float and needs to be the MIDDLE of the block (when going left/right) -- IE, 2.5 rather than 3.  If you give an integer, then it seems to be that it RANDOMLY picks which side to go based on something else, though it usually stays on the lower side...  so, by setting the offset to be 0.5 it always ends up in the right place.  This applies to Item Frames (the MCDungeon paintings) plus the 'real' paintings.

I will be sending a pull req to fix the landmarks shortly.

**Comment by sshipway** [comment]
Fixed in pull req #342  (I think)

I notice that the MCD function already adds the fractional parts to the TileX/Y/Z tags, but it seems that this is causing an issue with 1.9 needing it differnet in some way.  I set it to 8.0 (instead of 8) and it seems to work.  No idea why, only the left/right seems to be affected.

**Comment by orphu** [comment]
Merged
