### ISSUE TITLE
Update landmark sign format to latest

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#339]
The signs in landmarks (Graveyard, Well, Signpost) are in legacy format.  These should be updated to 1.9 JSON format.

At the same time, it would be amusing if the graveyard had a random chance of making the grave name "@p" (the player's own name) since this is now possible.

**Comment by sshipway** [comment]
Looking at the latest code, I see this has been done by retrofitting it to  addsign().  I've added an addsignJSON() to allow JSON-format entries but otherwise this can be closed

**Comment by orphu** [comment]
See #253 

A general purpose function is planned for 0.15.1
