### ISSUE TITLE
Portcullis commands kick clients on MP servers

### ISSUE THREAD

**Issue by orphu** [orphu/mcdungeon#346]
If a player presses either button they get kicked with an error. 

![2016-04-03_19 26 46](https://cloud.githubusercontent.com/assets/651179/14235653/39431312-f9d2-11e5-9245-688ec60d4960.png)

**Comment by orphu** [comment]
Looks like this was a 1.9.0 bug. Updating server and client to 1.9.2 fixed it.

**Comment by JiFish** [comment]
Maybe up the minimum version to 1.9.2?

**Comment by orphu** [comment]
Good call.
