### ISSUE TITLE
Multi threaded / multi process scanning

### ISSUE THREAD

**Issue by orphu** [orphu/mcdungeon#352]
I've been playing around with this using concurrent.futures and I've had some great results. I think I can get this in for the next release. There is some overhead. If you just run one thread it's a bit slower, but two threads are 25% faster and it just gets better from there. 

So far, I've implemented multi process scanning for the chunk scanner and the dungeon/thunt scanner.

**Comment by orphu** [comment]
Oh, I should add this will create a new dependency, which is the backport of futures to Python 2.x. This is in PIP though, so it's pretty easy to deal with.

**Comment by orphu** [comment]
Some stats:

This is on a Macbook Pro (El Capitan) i7-4850HQ CPU @ 2.30GHz (4 cores +hyperthreading)

The map is 88044 chunks, and I'm using a cut down version of the default config that only allows basic rooms, blank floors and features etc, and add one 4x4x1 dungeon.

MCD Version | workers | chunk scan | dungeon/thunt scan | total time 
------------ | ------------- | ------------- | ------------- | ------------- | -------------
0.15.1 dev | 1 | 9:27 | 2:14 | 11:47 
0.15.1 threads | 1| 6:17 | 2:29 | 8:53 
0.15.1 threads | 2| 4:19 | 1:17 | 5:44
0.15.1 threads | 4| 4:27 | 0:55 | 5:29 
0.15.1 threads | 8| 4:25 | 0:47 | 5:19 

There are some improvements to be made. On my test machine with about 4 processes the workers finish scanning all chunks faster than the main process can collect the results. This creates a bit of a bottleneck. Some optimization of the collection process is in order. The dungeon/thunt scan collection process doesn't have this problem, and you can see it scales up better.

**Comment by orphu** [comment]
Made a few easy optimizations already. 

MCD Version | workers | chunk scan | dungeon/thunt scan | total time 
------------ | ------------- | ------------- | ------------- | ------------- | -------------
0.15.1 dev | 1 | 9:27 | 2:14 | 11:47 
0.15.1 threads | 1| 5:49 | 2:28 | 8:23 
0.15.1 threads | 2| 3:01 | 1:17 | 4:26
0.15.1 threads | 4| 1:53 | 0:53 | 2:53 
0.15.1 threads | 8| 1:48 | 0:47 | 2:42
0.15.1 threads | 16 | 1:53 | 0:49 | 2:50

I added 16 workers for fun here. You can see on this hardware this is too much and the overhead of task switching becomes a liability. The sweet spot for me is 4-8 workers since I have 4 hyperthreaded cores. 

Seems to be right on the money though! 4.3 X improvement over the single threaded version on my four core CPU!

**Comment by orphu** [comment]
I optimized what chunks get sent to workers, and lowered the amount of data being pickled out to the sub processes for the dungeon/thunt scan. This was causing some slowness when scanning maps where the cache was very fresh. 

Current stats:

With an empty cache:

MCD Version | workers | chunk scan | dungeon/thunt scan | total time 
------------ | ------------- | ------------- | ------------- | ------------- | -------------
0.15.1 dev | 1 | 9:27 | 2:14 | 11:47 
0.15.1 threads | 1| 5:47 | 2:35 | 8:31 
0.15.1 threads | 2| 2:58 | 1:15 | 4:21
0.15.1 threads | 4| 1:55 | 0:54 | 2:56 
0.15.1 threads | 8| 1:47 | 0:48 | 2:42

With a very fresh cache (only 3 chunks to update):

MCD Version | workers | chunk scan | dungeon/thunt scan | total time 
------------ | ------------- | ------------- | ------------- | ------------- | -------------
0.15.1 dev | 1 | 0:09 | < :01 | 0:15 
0.15.1 threads | 1| < :01 | < :01 | 0:05 
0.15.1 threads | 2| < :01 | < :01 | 0:05 
0.15.1 threads | 4| < :01 | < :01 | 0:05 
0.15.1 threads | 8| < :01 | < :01 | 0:05

**Comment by orphu** [comment]
I've pushed this into the dev branch. Hope I didn't break everything. :)

Feedback appreciated!

**Comment by orphu** [comment]
This seems to completely break on windows. The sub processes appear to enter at main.

**Comment by orphu** [comment]
Yeah... Need to rework the mcdungon.py file. It's ugly anyway. Sorry for the breakage. dev will be broken for a little bit on Windows until I work through this.

**Comment by orphu** [comment]
I've reverted this in dev. This approach will not work on Windows, due to how multiprocessing uses os.spawn() instead of os.fork() on that platform. (Win32API has no fork() support...I forgot)

Really a shame. Will need to rethink this a bit. 

I'll push the multiprocessing version as a new branch to continue to experiment.

**Comment by orphu** [comment]
This is in the repo as the "workers" branch.

**Comment by sshipway** [comment]
Can you make it detect Windows, and force it to default to threads=1 if found.  Otherwise honour the setting in the config file.

**Comment by orphu** [comment]
Yeah, that's the route I'm going to go essentially. --procs=1 won't work either though. The main problem is that the world object would need to be passed to each sub-process under Windows,  which means it would need to be pickled for each function call. So in my example map it would be pickling the world object 88,000 times. That's going to be extremely slow. And come to think of it, that object probably can't be pickled. Major problems. 

I think I'll make a special case for --procs=0 that shuts to a slightly different code path that will do all the work in the main process. I'll just need to force Windows platforms to use --procs=0. 

The benefit to Linux/OS X is pretty great. I can work on a solution for Windows in the future.

**Comment by mathuin** [comment]
Out of curiosity, have you guys looked at OpenCL and friends?  It might be nice to use those graphics cards to offload your processing.  I used it for one of my projects and it really helped -- I only stopped maintaining the project because pymclevel frustrated me too much, glad to see you guys have a higher tolerance. :-)

**Comment by orphu** [comment]
Oh, interesting! Thanks!

**Comment by orphu** [comment]
I've disabled multiprocessing for Windows, and forced the workers = 1 case to use that code path. The overhead works against it with only one worker. This makes the workers = 1 case a bit faster. Good news is that even without multiprocessing the Windows version benefits from the other optimization that was done as part of this. 

Current stats. With an empty cache:

MCD Version | workers | chunk scan | dungeon/thunt scan | total time 
------------ | ------------- | ------------- | ------------- | ------------- | -------------
0.15.1 dev | 1 | 9:27 | 2:14 | 11:47 
0.15.1 threads | 1| 5:27 | 2:16 | 7:51 
0.15.1 threads | 2| 2:56 | 1:15 | 4:20
0.15.1 threads | 4| 1:52 | 0:52 | 2:53 
0.15.1 threads | 8| 1:44 | 0:48 | 2:41

With a very fresh cache (only 3 chunks to update):

MCD Version | workers | chunk scan | dungeon/thunt scan | total time 
------------ | ------------- | ------------- | ------------- | ------------- | -------------
0.15.1 dev | 1 | 0:09 | < :01 | 0:15 
0.15.1 threads | 1| < :01 | < :01 | 0:05 
0.15.1 threads | 2| < :01 | < :01 | 0:05 
0.15.1 threads | 4| < :01 | < :01 | 0:05 
0.15.1 threads | 8| < :01 | < :01 | 0:05

**Comment by orphu** [comment]
Merged back into dev.

**Comment by JoeFowlerJDi** [comment]
I'm getting a KeyError on maps that haven't been run through 1.9 with the new scan. Much like the one I just fixed here: 04d4ea6b7970c6ba45903925ed396f2d7abea970

But in this case, I am not sure how to best handle the missing value.

```
Finding good chunks:
Pass 1: 100%[========================================================>] 0:00:00
Pass 2:  80%[============================================>            ] 0:00:02Exception in main loop. Exception info below:
Traceback (most recent call last):
  File "C:\Users\JiFish\repos\mcdungeon\mcdungeon.py", line 2028, in <module>
    sys.exit(main())
  File "C:\Users\JiFish\repos\mcdungeon\mcdungeon.py", line 1788, in main
    (cx, cz, result, biome, depth) = classifyChunk(c)
  File "C:\Users\JiFish\repos\mcdungeon\mcdungeon.py", line 532, in classifyChunk
    chunk.root_tag['Level']['LightPopulated'].value == 0 or
  File "C:\Users\JiFish\repos\mcdungeon\pymclevel\nbt.py", line 353, in __getitem__
    raise KeyError("Key {0} not found".format(key))
KeyError: 'Key LightPopulated not found'
```

**Comment by JiFish** [comment]
I'm getting a KeyError on maps that haven't been run through 1.9 with the new scan. Much like the one I just fixed here: 04d4ea6b7970c6ba45903925ed396f2d7abea970

But in this case, I am not sure how to best handle the missing value.

```
Finding good chunks:
Pass 1: 100%[========================================================>] 0:00:00
Pass 2:  80%[============================================>            ] 0:00:02Exception in main loop. Exception info below:
Traceback (most recent call last):
  File "C:\Users\JiFish\repos\mcdungeon\mcdungeon.py", line 2028, in <module>
    sys.exit(main())
  File "C:\Users\JiFish\repos\mcdungeon\mcdungeon.py", line 1788, in main
    (cx, cz, result, biome, depth) = classifyChunk(c)
  File "C:\Users\JiFish\repos\mcdungeon\mcdungeon.py", line 532, in classifyChunk
    chunk.root_tag['Level']['LightPopulated'].value == 0 or
  File "C:\Users\JiFish\repos\mcdungeon\pymclevel\nbt.py", line 353, in __getitem__
    raise KeyError("Key {0} not found".format(key))
KeyError: 'Key LightPopulated not found'
```

**Comment by orphu** [comment]
Doh. I guess LightPopulated is new in 1.9. Thanks!

**Comment by orphu** [comment]
Curiously, I didn't have this issue in a 1.8 generated map. Not sure when TerrainPopulated and LightPopulated showed up. I'll have to put in a fallback.

**Comment by JiFish** [comment]
You should be able to reproduce it with the map I posted here. https://github.com/orphu/mcdungeon/issues/350#issuecomment-206558473 Maybe the original generation was earlier than 1.8, I'm not sure.
