### ISSUE TITLE
Landmark paintings cannot be removed from their item frames

### ISSUE THREAD

**Issue by mb243** [orphu/mcdungeon#353]
I've had several complaints about players not being able to remove landmark paintings (such as Mona Lisa) from their item frames. The painting can be right-clicked to be rotated, but doesn't detach when hit.

Any suggestions on how to get this resolved? I'm happy to supply more info if needed.

This server is running CraftBukkit version git-Spigot-e6f93f4-935f18b (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
McDungeon 0.15.0

Just leaving this here for myself: Mona Lisa X-169 Y65 Z1996

**Comment by sshipway** [comment]
I'm not sure how I would make framed maps (which is what they are of course, calling them paintings is confusing) non-detachable if I wanted to... but it may be that 1.9 now honours the Invulnerable tag, and line 444 in landmarks.py says:
````
framed_painting['Invulnerable'] = nbt.TAG_Byte(1)
````
So, although 1.8 still allows it to be broken, 1.9 now prevents it.  I can remember doing this originally to stop frames from being broken off and forgot about it when it didn't work.

**Comment by sshipway** [comment]
In summary, I'd say it is working as designed; however that doesn't mean it was a good design ;)

Since I'm responsible for writing that piece of code, I'm more than happy for it to be commented out if @orphu thinks it is better removed?

**Comment by mb243** [comment]
Thanks for the fast and informative updates :)

I'll wait to hear back on if this will get changed in the future. 

In the meantime, is there any way of removing the invulnerable tag on the currently-placed entity to see if it helps? I'm not  terribly familiar on to do this, so if you could throw a hint in my direction, I'd like to give it a try.

**Comment by sshipway** [comment]
If you want to stop this happening in the future, just comment out the line I specified above.  It's in landmarks.py

To change existing tile entities, I think the easiest way to do it would be to go into the game as an Op, then just break the frame yourself (which should drop the map).  Then re-create it with a NEW frame (dont re-use the one you just broke) and place the map into it.  The new frame will not have the Invulnerable tag.

Alternatively, you could use
````
/blockdata -169 65 1996 {Invulnerable:0}
````
this will probably do the job as well...

**Comment by orphu** [comment]
Makes me wonder if the Invulnerable tag might work on other things outside adventure mode. Locked chests?

**Comment by mb243** [comment]
Ahh, thank you! I'll try this tomorrow. 

Thanks again for the fast responses :)

**Comment by sshipway** [comment]
It would be really, _really_ good if Invulnerable works on locked chests in 1.9.  This would make so many things in the Treasure Hunts better, and would allow the final chests in Dungeons to be locked (with the key hidden somewhere in the dungeon).  Really have to test this.

**Comment by JiFish** [comment]
I just tried out chests using /blockdata and it didn't seem to work for me. :(

**Comment by orphu** [comment]
Too bad. :(

**Comment by mb243** [comment]
Welp, that didn't go as well as I had hoped.

I tried /blockdata and got "The target block is not a data holder block." 

Tried it with the XYZ of the space the item frame occupied, as well as the XYZ of the block it was attached to. Both generated the same message. 

So I went to blows with the item frame (from the back) in creative, and nothing happened. I punched it from the front, and... no more map. 

I should point out that I am op level 4, so that shouldn't be an issue. 

Any other suggestions at this point?

Also, is there any way to re-create this map from within the game, perhaps via "/summon ItemFrame ..." or no?

**Comment by sshipway** [comment]
Hmm, thinking about it more, if I remember correctly, frames are in fact entities, not tile entities, as they are not actually tied to a block (you can have up to 4 frames in a single air block).  So maybe /blockdata was the wrong command to use... maybe instead should use /entitydata?
````
/entitydata @e[type=ItemFrame,r=5] {Invulnerable:0}
````
Though, the selector may be wrong, as I would need to check the Entity type and probably add something to limit the selector to nearby.

**Comment by mb243** [comment]
The /entitydata command is the fix. FWIW, I put the following command in a repeating command block in a spawn chunk:

`/entitydata @e[type=ItemFrame] {Invulnerable:0}`

Should fix every frame as players discover them.

Thanks for the help!
