### ISSUE TITLE
Multi_* spawners broken in 1.10 

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#361]
Spawners using the SpawnPotentials tag seem to be broken with 1.10. Possibly this has been broken since 1.9.

Related to #359 as I wanted to use SpawnPotentials in Zombie_Villager.nbt. And #360

**Comment by JiFish** [comment]
I think maybe they need initial spawn data. The wiki says you can just set Delay to -1, but that doesn't seem to work for me.

**Comment by JiFish** [comment]
Confirmed, all the multi_ spawner NBTs are broken. Luckily, they aren't used in any of the default configs. If we really have to we can remove them. Still, I'd like to figure out what the issue is here.

I've attached my most recent attempt. Based on the [wiki documentaion](http://minecraft.gamepedia.com/Spawner#Data_values). The first spawn works as expected, but then the spawner just switches to the pig model and stops. Can anyone shed some light on this?

[Zombie_Villager.zip](https://github.com/orphu/mcdungeon/files/307624/Zombie_Villager.zip)

**Comment by Kovak** [comment]
SpawnPotentials no longer uses the weird split where you declare Type and
then Properties, you now should have everything under an Entity tag that is
just the entire entity tag as it normally would be. The only other thing is
a "Weight" tag. I haven't looked at the latest mc version, but this was the
case when I got my gui mob tool working with 1.9 a few weeks ago.

**Comment by JiFish** [comment]
Excellent! Thank you, this did seem to work. Oddly, fixing the Type/id split alone was not enough. It's also one or more of the other tags. I can now finish #359.

Thank you for writing that tool, I'll try to remember it first next time!
