### ISSUE TITLE
Replace NBT data files with YAML-formatted NBT tags

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#362]
Replace NBT data files with text files containing JSON-formatted NBT tags. This is for both items and spawners. (Maybe books.) 

Advantages: easier to edit, works with existing item generators, can be tracked by source control.

There are two possibilities here: single files with one entry per line (or better, separate config sections), or multiple files in separate folders like now. I slightly favour the former. magic_items.txt could be combined with the other custom items.

**Comment by sshipway** [comment]
I definitely like being able to specify these as JSON rather than NBT.  Not only is nbtedit a pain in the neck, but being able to track changes is a big win.

However I'd vote for one file per items; the reason being that it allows you to have general free-form multi-line formatting in the file to make it clearer to read.  Having a separate directory to hold all the files isn't that different from having one file with an entry per line in terms of organisation.

If you want a single file, then possibly have a special separator between sections rather than one per line?  Though if you're going this far you may as well go the multi-file route.

**Comment by JiFish** [comment]
I was thinking configparser supports multi-line values. But you're right, if it's going to be multi-line anyway, merging in to one big file doesn't really have an advantage,

**Comment by sshipway** [comment]
I think multi-file makes user contributions/submissions easier, and also if people want to upgrade but keep their new item or spawner definitions.

**Comment by orphu** [comment]
I like separate files.

**Comment by JiFish** [comment]
There are two major hurdles to implementing this.

1. Minecraft uses an extended version of JSON
JSON has not concept of a byte, or char or several of the other data types NBT uses. To compensate for this, they have created a custom extension of JSON which allows you to specify some types e.g. `key: 1b` for a byte or `Key 5.0f` for a float. This means that even if we found a good JSON library, we may have to look in to extending it.

2. Even more concerning: in some cases you don't have to specify the type.
In these cases Minecraft instead uses the type it expected for that key. Given the number of potential key/types in the game, it seems labour prohibitive to replicate this behaviour. If we didn't do that our syntax would be _close_ to that used in commands, but much stricter. This could lead to a lot of confusion. (If it's even possible. How do you specify a Char, Int or Long in MC's command JSON format?)

**Comment by JiFish** [comment]
The above issues make me think #332 is a better direction to go. Loot Tables are already in the JSON text format. Let minecraft process them instead.

**Comment by orphu** [comment]
Maybe YAML instead of JSON for spawners? I already use the nbtedit tool from [nbt2yaml](https://pypi.python.org/pypi/nbt2yaml) to edit NBT files.

**Comment by JiFish** [comment]
Agreed. The major advantage of JSON would be the ability to use the same JSON as, for example, a give command. Since we can't do that, switching to a better format would seem to be the way to go.

**Comment by orphu** [comment]
(Really should remove PyYaml and treat it as a dependency)

**Comment by JiFish** [comment]
I've got something working using nbt2yaml's parse_yaml function. Unless you specifically didn't want to have nbt2yaml as a dependency?

**Comment by JiFish** [comment]
The documentation repo also needs updating to reflect this change.

**Comment by orphu** [comment]
Okay, great!

**Comment by orphu** [comment]
The YAML files seem to be incomplete. They are missing the 'id' field, for example. I'm going to work around it by grabbing a "template" of sorts for spawners from utils.get_tile_entity_tags() (working on that now) and then having the loadyaml() function just replace any tags that get loaded from the files. That way we can be sure to catch any future mandatory tags, and the YAML files can be sparse.

**Comment by JiFish** [comment]
To be clear, you are saying that the missing tags are now required when they once weren't? (Not that nbt2yaml has failed to include some tags during the conversion.) If so, this could be a candidate for #403

I did try a selection of the custom spawners post-yaml change, so I know at least some of them must work.

That said, your 'template' seems like a good idea. It seems every update a tag that was formally optional becomes required or they add a new one. Ensuring a complete structure will likely save us a lot of work in the future.

**Comment by orphu** [comment]
So, turns out I sort of caused this myself, but I'm still going to add an optional "defaults" entity when using tagsfromfile(). Like you say, seems like it would save a lot of pain down the road. 

In general we can then rely on the entity building functions as a source of truth on entity tags.
