### ISSUE TITLE
Win 64 Download

### ISSUE THREAD

**Issue by createaflow** [orphu/mcdungeon#365]
The win 64 download file fails when I try to download marking "Network Error."  Is there an alternative download?
Thanks!! :-)

**Comment by JiFish** [comment]
https://github.com/orphu/mcdungeon/releases/download/v0.16.0/mcdungeon-v0.16.0-win64.zip

Where did you find the broken link?

**Comment by createaflow** [comment]
Here: https://github.com/orphu/mcdungeon/releases/tag/v0.16.0

**Comment by JiFish** [comment]
That's where I got the link I posted and it's working fine for me. Possibly a network problem at your end?

**Comment by createaflow** [comment]
Possibly, though _ can't begin to image what it is. Whatever the case, the link you offered worked excellently, so I thank you kindly for your quick assistance. Much, much appreciated!!!
:+1:
