### ISSUE TITLE
MCDungeon 0.17.0 and Minecraft Exploration Update Discussion

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#371]
Has anything broken in the latest snapshot?

**Comment by JiFish** [comment]
The new Display > MapColor tag on maps will allow us to tint dungeon maps a specific colour. This matches the behaviour of the new maps. Ocean (Blue), Woodland (Brown). Perhaps ours could be red?

Does the Locked tag work with the new Shulker Box? If so, there's finally a way of locking away loot. However, the contents of the chest is probably won't be worth the price of the box. :)

**Comment by DrakDragon** [comment]
> The new Display > MapColor tag on maps will allow us to tint dungeon maps a specific colour. This matches the behaviour of the new maps. Ocean (Blue), Woodland (Brown). Perhaps ours could be red?

Actually if possible, could the color be user dependent? Defaulting to Red, but with the ability to specify what color you want that particular dungeon's maps to be.

**Comment by JiFish** [comment]
I don't see why not.

**Comment by JiFish** [comment]
It looks like 1.11 is stricter with requiring the "minecraft:" prefix on ids. This might be what is causing #372 and may also be effecting #363.

**Comment by JiFish** [comment]
I don't have as much time for testing as I used to. Once the dev version is relatively stable, I might ask on the Minecraft Forum and possibly reddit for testers, Unless @orphu has any objection?

**Comment by JiFish** [comment]
If this bug gets fixed: https://bugs.mojang.com/browse/MC-109306 It will finally be possible to do locked box puzzles.

**Comment by sshipway** [comment]
That looks like a great solution to the problem of having locked boxes in treasure hunts to enforce the sequence, and having a locked final loot chest in a dungeon.  You can mine it and pick it up, but still not get into it without the key...  since even in survival maps you still cant get into a locked shulker box without a key.

**Comment by JiFish** [comment]
Yup, an exciting development. And that bug is now marked as resolved.

**Comment by JiFish** [comment]
I believe I have made all the necessary changes for Minecraft 1.11, but it could desperately use some additional testing.

Does anyone have any insight in getting the build script to work under Windows? I have used pip to install pyinstaller but get:
```
JiFish@Jane MINGW64 ~/repos/mcdungeon/extras (development)
$ bash build-mcdungeon-pyinstaller.sh
Platform is win
Removing old git repo...
Cloning into 'mcdungeon'...
remote: Counting objects: 7797, done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 7797 (delta 20), reused 0 (delta 0), pack-reused 7719
Receiving objects: 100% (7797/7797), 5.87 MiB | 469.00 KiB/s, done.
Resolving deltas: 100% (4508/4508), done.
Checking connectivity... done.
Submodule 'pymclevel' (https://github.com/orphu/pymclevel.git) registered for path 'pymclevel'
Cloning into 'pymclevel'...
remote: Counting objects: 4487, done.
rRemote: Total 4487 (delta 0), reused 0 (delta 0), pack-reused 4487eceiving obje

Resolving deltas: 100% (2617/2617), done.
Checking connectivity... done.
Submodule path 'pymclevel': checked out 'd5abd5dea415a16b53e6f6d5116ef65ef10d433e'
MCDungeon Version is v0.16.0
Build name will be: mcdungeon-v0.16.0-win64
C:\Python27\python.exe: can't open file 'makespec.py': [Errno 2] No such file or directory

FATAL: Makespec step failed.
```

**Comment by JiFish** [comment]
I can confirm Locked Shulker Boxes work in 16w44a

**Comment by JiFish** [comment]
Minecraft 1.11 has entered pre-release, so I'd like to push for release. Lack of extensive testing aside, the development version works with 1.11 far better.

**Comment by orphu** [comment]
Thanks for all your hard work. I'm for a release, but I'd like to get the docs updated first.

**Comment by JiFish** [comment]
Yup, I'll get on that.

**Comment by JiFish** [comment]
Slipped under my radar. But 1.11 has now been out for a few days.

**Comment by orphu** [comment]
I somehow missed your updates to the docs. I'll see about a build.

**Comment by orphu** [comment]
Released!
