### ISSUE TITLE
Validate input for X size, Z size and levels immediately in interactive mode.

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#373]
Validate input for X size, Z size and levels immediately in interactive mode. The current behaviour is to spit out an obtuse error later.

**Comment by JiFish** [comment]
Default being missing from the configurations list is a little confusing. A new user might think one of the listed configs is the default and not know which one it is.

Suggest default should always be listed as option [1]

**Comment by orphu** [comment]
Sounds good
