### ISSUE TITLE
Flower Pots now use entity data rather than DV for flower type

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#381]
Flower Pots now use entity data rather than DV for flower type. This has broken those used in generation.

**Comment by sshipway** [comment]
Lots of these are used in the treasure hunts as well (in the graveyard and somewhere else I think)

**Comment by JiFish** [comment]
I found the one in the graveyard, but I couldn't see any others in landmarks. Unless I've missed something?

Features
=====
- TripleStairs
- SecretStudy
- SecretShop
Landmarks
=====
- Graveyard
Ruins
=====
- HouseFrame

**Comment by sshipway** [comment]
The graveyard uses a lot (most graves should get one), but its only one place in the code fortunately.  Maybe I misremember the others, so its only one place to fix.

**Comment by JiFish** [comment]
Looks like this has been broken for some time.

For the shops, study and graveyard I added more possible flowers. House Frame was a bit tricky because it places the block softly. I just made these empty pots. I think that still fits the theme.
