### ISSUE TITLE
0.17.1 Release

### ISSUE THREAD

**Issue by orphu** [orphu/mcdungeon#389]
Looks like a few bugs are popping up. I'm out of town at a conference until next week. I'll look at a 0.17.1 release then.

**Comment by JiFish** [comment]
Fortunately nothing save-breaking. It would be nice to see how it runs with the 1.11.1 snapshot too, so I don't think there's a particular hurry.

**Comment by JiFish** [comment]
I've been under the weather lately, but I'll have a crack at getting #396 and #395 done before you release. If I'm too slow, just go ahead and release. Neither of these are vital.

**Comment by JiFish** [comment]
@orphu OK, it should be good to go, now.

**Comment by orphu** [comment]
0.17.1 posted
