### ISSUE TITLE
Can't get the 0.17 release to work

### ISSUE THREAD

**Issue by DrakDragon** [orphu/mcdungeon#391]
Downloaded the 0.17 release for 1.11 and got the following message when running the launcher:

Error loading Python DLL: C:\Users\<name>\AppData\Local\Temp\_MEI33362\python27.dll (error code 14001)

Any ideas?

**Comment by JiFish** [comment]
Can confirm this occurs in the 0.17 win 64 build. Could this be a problem with PyInstaller @orphu?

As a workaround, you can try the python version instead.

**Comment by orphu** [comment]
Er.. hum. Works here (Windows 10 64 bit). Maybe a corrupt upload (though, I'd think zip would take care of that). Same build environment as 0.16.0. 

I've re-zipped and re-uploaded the 0.17.0-win64 package in the release section. Try that and let me know if it's any different.

**Comment by DrakDragon** [comment]
No dice, downloaded it and tried it, get the same result sadly.

**Comment by JiFish** [comment]
Same. I'm using Windows 7, perhaps the difference is there? What is your OS @DrakDragon?

**Comment by JiFish** [comment]
Could it potentially be this? http://stackoverflow.com/questions/32457341/pyinstaller-and-onefile-build-causes-error-loading-python-dll-error-code-14001

**Comment by DrakDragon** [comment]
I'm using Windows 7 64 bit. Previous versions of McDungeon have worked, though.

**Comment by orphu** [comment]
Try this one. I added the --clean option. 

[0.17.0](https://drive.google.com/open?id=0B6TnX-hXKti2NGFRRTdsSDFxUzQ)

**Comment by DrakDragon** [comment]
Aha, there we go, it works!

Thanks!

**Comment by orphu** [comment]
Great! I'll add that to the build script.

**Comment by orphu** [comment]
Updated the package on the release page.

**Comment by JiFish** [comment]
Working great. Thanks, orphu.

**Comment by orphu** [comment]
I've not checked this in yet. Re-opening as a reminder.

**Comment by JiFish** [comment]
Apologies, I hit 'Close and comment' instead of comment.
