### ISSUE TITLE
MCDungeon has lost track of a few

### ISSUE THREAD

**Issue by MikeyCarter** [orphu/mcdungeon#394]
Could understand why my refresh/regen script wasn't updating one of my dungeons... then I noticed:

```
Known dungeons on this map:
+-----------+----------------+---------+-------+----+-------------------------+
|       Pos |      Date/Time |     Ver |  Size | Lv |                    Name |
+-----------+----------------+---------+-------+----+-------------------------+
| 1408 1088 | 01/10/17 23:08 |  0.17.0 |   4x4 |  4 |   Elder Fraedae's Tower |
| 640 -1200 | 01/10/17 23:07 |  0.17.0 |   4x4 |  4 |          Cruel Fortress |
|  -816 992 | 01/10/17 23:08 |  0.17.0 |   4x4 |  4 |       Grizzly Catacombs |
|   720 192 | 01/10/17 23:08 |  0.17.0 |   7x7 |  3 | Prefect Numiciussca's H |
|   496 544 | 01/10/17 23:07 |  0.17.0 |   7x7 |  3 |       Putrid Runestones |
+-----------+----------------+---------+-------+----+-------------------------+

```
... a few are missing.   Used to have at least 7.   Is there a way to re-scan or check for missing ones?

**Comment by JiFish** [comment]
You could try deleting. mcdungeon_cache in your save and allowing MCDungeon to regenerate it.

I could be wrong here, since I've done very little with the dungeon placement stuff, but I do have an idea: Each dungeon is generated with a hidden chest with book with meta-data on the dungeon. If that book was missing, it might cause MCDungeon to 'lose' the dungeon.

**Comment by orphu** [comment]
Yup JiFish has it right. Best option is to delete your cache and rescan. Any chance your books could have been modified in some way? 

How old were these dungeons do you suppose? Any idea which version they were last regenerated with?

**Comment by MikeyCarter** [comment]
Could be 0.16 or 0.17 they were created with.

So how do I open the chest to examine the book?  And if it's corrupt or missing how do I fix?

![2017-01-11_22 47 56](https://cloud.githubusercontent.com/assets/1325499/21876359/3cf98290-d850-11e6-9500-d4e9545c224c.png)

**Comment by MikeyCarter** [comment]
Oh and I did clear the cache and even tried restoring the cache from earlier copies.

**Comment by orphu** [comment]
Do you see any errors when re-scanning? Something like "Non-book or odd book found in chest"

To open the chest, you'd have to overwrite the Lock tag with a known value. You can then hold an item with the same name to unlock it. Or you could use an editor to remove the Lock tag. Unless there is a way to delete a tag in game... not sure! 

Something must have corrupted (or deleted) the book in there. Reconstructing them would be hard... If you know the size of the dungeon, you could possibly just manually generate a new one in place?

**Comment by MikeyCarter** [comment]
Figured out a creative way to get the book in/out... hoppers.   Kinda makes the locks meaningless.

![2017-01-12_22 10 03](https://cloud.githubusercontent.com/assets/1325499/21917299/cc067406-d914-11e6-81b6-f1063717ec8b.png)
![2017-01-12_22 10 05](https://cloud.githubusercontent.com/assets/1325499/21917272/adaa4ac8-d914-11e6-8d5e-a6637dd4ce21.png)
![2017-01-12_22 10 08](https://cloud.githubusercontent.com/assets/1325499/21917276/afb5b50a-d914-11e6-8ae3-9797d94a3fe2.png)
![2017-01-12_22 10 10](https://cloud.githubusercontent.com/assets/1325499/21917277/b2a14c66-d914-11e6-856c-dbcf09787246.png)
![2017-01-12_22 10 12](https://cloud.githubusercontent.com/assets/1325499/21917279/b47078d2-d914-11e6-8b3f-606bd61427bc.png)
![2017-01-12_22 10 13](https://cloud.githubusercontent.com/assets/1325499/21917280/b603c5a0-d914-11e6-845a-e214ad7a8570.png)
![2017-01-12_22 10 16](https://cloud.githubusercontent.com/assets/1325499/21917283/b73d8d0c-d914-11e6-9907-0f34f2b324f5.png)
![2017-01-12_22 10 18](https://cloud.githubusercontent.com/assets/1325499/21917285/b87fc8ce-d914-11e6-8a63-1b9ffd711066.png)
![2017-01-12_22 10 20](https://cloud.githubusercontent.com/assets/1325499/21917286/b9d56120-d914-11e6-862c-b2d8cf0c7bde.png)
![2017-01-12_22 10 23](https://cloud.githubusercontent.com/assets/1325499/21917287/bb2c8cec-d914-11e6-9453-1d28ff368d2f.png)
![2017-01-12_22 10 25](https://cloud.githubusercontent.com/assets/1325499/21917289/bc70fb92-d914-11e6-8761-1fc5e4824ae8.png)
![2017-01-12_22 10 26](https://cloud.githubusercontent.com/assets/1325499/21917292/bdfa4054-d914-11e6-8ad2-51d41e23488a.png)

**Comment by JiFish** [comment]
Locked chests are not supposed to be secure outside of adventure mode. You could have also mined the chest and just picked up the map that way.

Without actually decoding the text in the book, it looks fine. And this is from one of the dungeons that is not being found?

**Comment by MikeyCarter** [comment]
Yes.   So I've deleted the cache and checked the existence of the book... No errors being reported on screen.

Just re-ran so I could get you the output... seems one more just went missing and I haven't changed anything:

```
./mcdungeon.py list Narnia
MCDungeon 0.17.0
Loaded 403 materials.
Loaded 685 items.
Loaded 58 items from NBT files.
Trying to open: Narnia
Trying to open: /root/.minecraft/saves/Narnia
Loaded world: /root/.minecraft/saves/Narnia (95450 chunks, 256 blocks high)
Looking for data directory: Narnia/data
Looking for data directory: /root/.minecraft/saves/Narnia/data
Scanning world for existing dungeons and treasure hunts:
Pass 1: 100%[========================================================>] 0:00:00
Pass 2: 100%[========================================================>] 0:00:10
Known dungeons on this map:
+-----------+----------------+---------+-------+----+-------------------------+
|       Pos |      Date/Time |     Ver |  Size | Lv |                    Name |
+-----------+----------------+---------+-------+----+-------------------------+
| 640 -1200 | 01/12/17 22:18 |  0.17.0 |   4x4 |  4 |          Cruel Fortress |
|   720 192 | 01/12/17 22:19 |  0.17.0 |   7x7 |  3 |  Consul Vinuminus' Hall |
|  -816 992 | 01/12/17 22:18 |  0.17.0 |   4x4 |  4 |       Grizzly Catacombs |
| 1408 1088 | 01/12/17 22:18 |  0.17.0 |   4x4 |  4 |  King Ariadesces' Tower |
+-----------+----------------+---------+-------+----+-------------------------+

Known treasure hunts on this map:
+-----------+----------------+---------+-------+----+-------------------------+
|       Pos |      Date/Time |     Ver | Range | St |                    Name |
+-----------+----------------+---------+-------+----+-------------------------+
|  1376 352 | 08/27/16 08:24 |  0.16.0 |  5-10 |  3 | Captain Edwarder's trea |
| -192 1536 | 08/27/16 08:24 |  0.16.0 |  5-10 |  3 |    Captain Jack's chest |
| 1552 1024 | 08/27/16 08:25 |  0.16.0 |  5-10 |  5 | Black Cocklylas' locker |
+-----------+----------------+---------+-------+----+-------------------------+
```

**Comment by JiFish** [comment]
Something must have changed in either the world save or the configuration file if you are getting different results. To be clear, has the world save been used at all between runs? Has it been played. modified dungeons in MCDungeon or run though another tool?

@orphu Does the max_dist and the spawn setting change which dungeons will be picked up in a scan?

**Comment by MikeyCarter** [comment]
I played a dungeon last night, and the server had been rebooted this morning.  

The new missing one: 

`1408 1088 | 01/10/17 23:08 |  0.17.0 |   4x4 |  4 |   Elder Fraedae's Tower `

Are in chunks that would not have even been loaded last night.   Although looking at Minecraft Overviewer it shows r.2.2.mca as being the area it's in:

`-rw-rw-r-- 1 minecraft dba 5812224 Jan 12 22:18 r.2.2.mca`

It was modified at that time but not by any editors.

**Comment by MikeyCarter** [comment]
Some more digging:

Added this to the mcdungeon.py's checkDInfo:

```
        # CF Edit Start
        if ('CustomName' in tileEntity ):
          f = open('/tmp/mcdungeon.txt', 'a')
          f.write("Chunk %s %s, Key %s, Entity %s, Custom %s\n" % (cx, cz, key, tileEntity['id'].value, tileEntity['CustomName'].value))
          f.close()
        # CF Edit End
```

Removed the cache and re-ran:

```
# cat mcdungeon.txt  | grep MC
Chunk -58 -48, Key -928,-768, Entity minecraft:chest, Custom MCDungeon THunt Data Library
Chunk -71 29, Key -1136,464, Entity minecraft:chest, Custom MCDungeon THunt Data Library
Chunk 40 -75, Key 640,-1200, Entity Chest, Custom MCDungeon Data Library
Chunk 31 34, Key 496,544, Entity minecraft:chest, Custom MCDungeon Data Library
Chunk 45 12, Key 720,192, Entity Chest, Custom MCDungeon Data Library
Chunk 86 22, Key 1376,352, Entity Chest, Custom MCDungeon THunt Data Library
Chunk -51 62, Key -816,992, Entity Chest, Custom MCDungeon Data Library
Chunk 9 17, Key 144,272, Entity minecraft:chest, Custom MCDungeon Data Library
Chunk 54 87, Key 864,1392, Entity minecraft:chest, Custom MCDungeon THunt Data Library
Chunk -5 6, Key -80,96, Entity minecraft:chest, Custom MCDungeon THunt Data Library
Chunk 25 -70, Key 400,-1120, Entity minecraft:chest, Custom MCDungeon THunt Data Library
Chunk -22 -5, Key -352,-80, Entity minecraft:chest, Custom MCDungeon Data Library
Chunk -83 6, Key -1328,96, Entity minecraft:chest, Custom MCDungeon Data Library
Chunk 97 64, Key 1552,1024, Entity Chest, Custom MCDungeon THunt Data Library
Chunk -12 96, Key -192,1536, Entity Chest, Custom MCDungeon THunt Data Library
Chunk 28 -7, Key 448,-112, Entity minecraft:chest, Custom MCDungeon Data Library
Chunk 17 95, Key 272,1520, Entity minecraft:chest, Custom MCDungeon Data Library
Chunk 88 68, Key 1408,1088, Entity Chest, Custom MCDungeon Data Library

```

```
 ./mcdungeon.py list Narnia
MCDungeon 0.17.0
Loaded 403 materials.
Loaded 685 items.
Loaded 58 items from NBT files.
Trying to open: Narnia
Trying to open: /root/.minecraft/saves/Narnia
Loaded world: /root/.minecraft/saves/Narnia (95450 chunks, 256 blocks high)
Looking for data directory: Narnia/data
Looking for data directory: /root/.minecraft/saves/Narnia/data
Dungeon cache missing, or is an old version. Resetting...
Treasure Hunt cache missing, or is an old version. Resetting...
Scanning world for existing dungeons and treasure hunts:
Pass 1: 100%[========================================================>] 0:00:00
Pass 2: 100%[========================================================>] 0:00:47
Known dungeons on this map:
+-----------+----------------+---------+-------+----+-------------------------+
|       Pos |      Date/Time |     Ver |  Size | Lv |                    Name |
+-----------+----------------+---------+-------+----+-------------------------+
| 640 -1200 | 01/12/17 22:18 |  0.17.0 |   4x4 |  4 |          Cruel Fortress |
|  -816 992 | 01/12/17 22:18 |  0.17.0 |   4x4 |  4 |       Grizzly Catacombs |
|   720 192 | 01/12/17 22:19 |  0.17.0 |   7x7 |  3 |  Consul Vinuminus' Hall |
| 1408 1088 | 01/12/17 22:18 |  0.17.0 |   4x4 |  4 |  King Ariadesces' Tower |
+-----------+----------------+---------+-------+----+-------------------------+

Known treasure hunts on this map:
+-----------+----------------+---------+-------+----+-------------------------+
|       Pos |      Date/Time |     Ver | Range | St |                    Name |
+-----------+----------------+---------+-------+----+-------------------------+
|  1376 352 | 08/27/16 08:24 |  0.16.0 |  5-10 |  3 | Captain Edwarder's trea |
| 1552 1024 | 08/27/16 08:25 |  0.16.0 |  5-10 |  5 | Black Cocklylas' locker |
| -192 1536 | 08/27/16 08:24 |  0.16.0 |  5-10 |  3 |    Captain Jack's chest |
+-----------+----------------+---------+-------+----+-------------------------+

```

**Comment by MikeyCarter** [comment]
Ok I see the issue, id:  minecraft:chest  vs Chest

**Comment by JoeFowlerJDi** [comment]
Nice work. Looks like the problem is to do with the changes tile entity IDs. We need to alter the checkDInfo function to search for all the different valid chest IDs.

**Comment by JiFish** [comment]
Nice work. Looks like the problem is to do with the changes tile entity IDs. We need to alter the checkDInfo function to search for all the different valid chest IDs.

**Comment by JiFish** [comment]
Thanks for investigating this. Your fix is now in the development branch.
