### ISSUE TITLE
Banners Base Colour is always black when it is an item reward.

### ISSUE THREAD

**Issue by ninmore** [orphu/mcdungeon#397]
When you generate a banner for a dungeon when the banner is placed in the dungeon such as in the secret shop or church room it is the correct base colour. But when the banner is an item reward in chests the base colour is always black. Here is a picture of the items, left is secret shop banner and the on the right it is wrong, the item drop one http://bit.ly/2kdKksK

And item details: http://bit.ly/2kdBzPe http://bit.ly/2kdL8hm

**Comment by JiFish** [comment]
Thanks for the detailed report. I can confirm this bug.

Either flag items store the background differently from flag entities, or I missed something in the last update.

**Comment by JiFish** [comment]
Interesting, setting the damage value on the item is necessary, but not on the entity. I wonder why Mojang did it this way? At any rate, I should be able to fix it.

**Comment by JiFish** [comment]
Fixed in development version and next release.
