### ISSUE TITLE
Portcullis Source Sound Error

### ISSUE THREAD

**Issue by ninmore** [orphu/mcdungeon#398]
Portcullis should play the piston open and close sound when you press the button, but it does not and throws and error on the server `[@: Source blocks is unknown]`. 

This fix for this is simple just update `/playsound minecraft:block.piston.contract blocks @p` to  `/playsound block.piston.contract block @p ~ ~ ~ 10 1` as a fix for this issue. This is under `hall_traps.py` but may have to be updated for any other rooms/traps that play sound.

**Comment by JiFish** [comment]
Thank you for the fix.

**Comment by JiFish** [comment]
Fixed in development and for next release.

**Comment by JiFish** [comment]
This would appear to be the only place we use the /playsound command so far.  In the future we might want to think about abstracting commands creation so if the commands are changed, we'd only need to update one place.
