### ISSUE TITLE
Minecraft 1.12 / MCDungeon 0.18.0

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#399]
The new terracotta blocks add some interesting possibilities for generation. I previously wanted floor types with geometric patterns, but found wool blocks too large. Manipulation of the terracotta blocks can produce some very neat patterns. #401

**Comment by JiFish** [comment]
@orphu: Suggestion: Remove the Lucky Blocks sample configuration. It was created for the 1.7 or 1.8 version of the mod. I have no idea if it still functions, but I doubt it. Leaving it in might be more confusing than helpful.

**Comment by orphu** [comment]
+1

**Comment by orphu** [comment]
For that matter, do the world guard and overviewer POI export export options still work? I don't keep up with that stuff, so I have no idea.

**Comment by JiFish** [comment]
Overviewer POI does still work. No idea about world guard.

**Comment by JiFish** [comment]
Any other ideas for the new blocks? I really like concrete powder as faux coloured sand, but it's so colourful it's tough to figure out where to put it.

I was toying with the idea of a 'scorched' feature. Basically a room that had been burnt to the ground. The floor would be white, grey and black powder, isolated blocks of wood and with a treasure chest hidden in the debris. Maybe some ever-burning netherrack?

**Comment by orphu** [comment]
I dunno on the concrete. The hardened clay colors are much more subdued and better suited for the whole dungeon aesthetic. 

I like the scorched idea. 

I had a couple of ideas for two new treasure rooms:

**Illager Library**: Long, deep room like a throne room, but with library stacks. An Illager guards the treasure. 

**Diamond Mine**: Large 2x2x2 open cave room. Multiple diamond and emerald ore veins. Corpse in the middle with leather armor (maybe enchanted, like the ones in the Barrow) with a treasure chest and a note. 100% silverfish in the cave walls.

**Comment by JiFish** [comment]
I can't see any place for concrete itself. I think the powder form has more possibilities because of it's novel mechanics.

I'm looking forward to some new treasure rooms!

**Comment by JiFish** [comment]
The wool colours are much brighter now too. Really makes some of the rugs stand out.

**Comment by orphu** [comment]
Illager Library

![2017-03-04_22 11 44](https://cloud.githubusercontent.com/assets/651179/23584218/8b5b69fc-0128-11e7-9807-87096e46f2f6.png)

![2017-03-04_22 12 04](https://cloud.githubusercontent.com/assets/651179/23584219/8f43ce4c-0128-11e7-89f0-8fc103e994a9.png)

![2017-03-04_22 12 26](https://cloud.githubusercontent.com/assets/651179/23584220/9395347c-0128-11e7-9471-ebd815af13cf.png)


And about half a second before I died. :) 

![2017-03-04_22 12 44](https://cloud.githubusercontent.com/assets/651179/23584221/974056c4-0128-11e7-861d-f9a6187ffedd.png)

**Comment by JiFish** [comment]
Really cool! Reminds me of the libraries in strongholds, but better. Since it's a library, you should hide some written books and maybe even enchanted books about the place. 

"New treasure-rooms" is the number one request from my server. So we're all looking forward to giving this a play. If you're looking for ideas for other treasure rooms, I thought a pool with guardians and treasure at the bottom would be a neat idea. ;) #217

**Comment by orphu** [comment]
I had the same idea! I was just adding some books to the shelves.

Right! I forgot about the guardian room ticket. :)

**Comment by JiFish** [comment]
@orphu: Bug in library. Redstone lamps are unpowered (even though they are generated as lit.) This means that a block update (e.g. mining a nearby block) causes them to go out.

Suggest either putting a redstone torch behind them, or maybe using Sea Lanterns or Jack O' Lanterns instead.

**Comment by orphu** [comment]
Oh right! Thanks!

**Comment by JiFish** [comment]
A crafty player has figured out that the portcullises can be mined for infinite resources. Nothing we can do about this, but maybe deserves note in the config file?

**Comment by orphu** [comment]
Heh! Yeah, endless fences I suppose.

**Comment by JiFish** [comment]
In this case, the player found a large double? triple? sized Iron Bars one and had several stacks after not much work. I thought it was ingenious.

**Comment by JiFish** [comment]
Here's what I had in mind for the scored feature. It needs some finesse yet.

I'd like to encourage more nearby wood to catch fire. So you'd go in to one of the great halls and the wooden balcony is already half destroyed. Maybe I should put some specific code in for specific rooms?

![2017-03-07_01 25 32](https://cloud.githubusercontent.com/assets/1314002/23637816/b7287de6-02d5-11e7-8b86-f99e88e05251.png)
![2017-03-07_01 24 26](https://cloud.githubusercontent.com/assets/1314002/23637830/c8b56e98-02d5-11e7-9088-1893d3250664.png)

**Comment by orphu** [comment]
Or maybe you could scan the room for wooden things and light them on fire.

**Comment by JiFish** [comment]
The new Knowledge Book item might make good loot for the library and study.

**Comment by JiFish** [comment]
The chunk DataVersion should probably be updated for this release.

**Comment by JiFish** [comment]
1.12 is now in pre-release.

**Comment by JiFish** [comment]
@orphu: 1.12 is going to release any day now. Suggest pushing anything unfinished to MCDungeon 0.19 and releasing what we have for 1.12 compatibility.

Again, I haven't given this as much testing as I'd like. But I'm pretty sure it is at least less broken than the previous version, particularly under Minecraft 1.12.

**Comment by orphu** [comment]
Sounds good. I saw a release date of June 7 somewhere. I had a burst of free time there for a little while, but it dried up. :)

**Comment by JiFish** [comment]
I'm going to split the remaining stuff in to it's own issues so I can close this thread.
