### ISSUE TITLE
New terracotta floor styles

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#401]
New floor styles based on the new terracotta blocks.

**Comment by orphu** [comment]
Looking forward to these, but I think they need to be rare. :)

**Comment by JiFish** [comment]
Agreed.

Firstly, the blocks are sort of expensive to make. So we don't want to give too many away. I remember the days when dyed wool was semi-expensive and players would go in to dungeons to steal the floors...

Secondly, as a abandoned dungeon is would make no sense to have lots of floors like this. They should be an occasional unusual find.

**Comment by JiFish** [comment]
I'm doing some tests to find patterns that work well with all 16 different pattens. I've got to say, some are very pleasing to the eye:

![2017-02-24_20 42 13](https://cloud.githubusercontent.com/assets/1314002/23320275/edf172c6-fad1-11e6-826f-d5102ee8a89a.png)

**Comment by JiFish** [comment]
After some deliberation these are the patterns I am going for, showing for each colour block: https://www.youtube.com/watch?v=Ij9Ur3G7j6o

**Comment by orphu** [comment]
Nice! Those would look cool in treasure rooms, like the throne room or end portal.

**Comment by JiFish** [comment]
Here are a couple of 'in-action' screen-shots. They are actually more garish than I imagined in place. You are definitely right that they should be a very rare occurrence by default. I'm also considering switching off the unbroken version entirely. 

Are there any colours you think we should exclude?

I'll be checking it in with some provisional values shortly. We can adjust them from there.

> Those would look cool in treasure rooms, like the throne room or end portal.

Great idea. Can I leave that to you? I suspect you'll be able to make that change faster than me.

![2017-02-24_21 42 16](https://cloud.githubusercontent.com/assets/1314002/23322358/6e5b022a-fadb-11e6-9080-73146fe3ad2f.png)
![2017-02-24_21 43 05](https://cloud.githubusercontent.com/assets/1314002/23322359/71e7421e-fadb-11e6-88fa-cc562f698608.png)
![2017-02-24_21 44 22](https://cloud.githubusercontent.com/assets/1314002/23322366/74eac3f0-fadb-11e6-8278-329684b65cdf.png)

**Comment by JiFish** [comment]
The defaults I have set make the mosaics twice as rare as a rug.

**Comment by JiFish** [comment]
Now I've finished, I'm wondering if I should have made it a meta-material. That would make it easier to use in various treasure rooms.

**Comment by orphu** [comment]
Oof. Yeah, some of those a rough to look at. :) 

I do think very rare in rooms and slightly more common in a treasure room makes them more dramatic. 

Meta material is a good idea.

**Comment by JiFish** [comment]
I've got something going with meta materials. I think this is a good way forward as it allows us to be more selective about what colours appear where, rather than rolling randomly every time.

**Comment by orphu** [comment]
There are some pretty complex things you can do. At some point I might want to look at something that can generate small complex patterns. 

![pic](https://cloud.githubusercontent.com/assets/651179/23331525/c53dcb40-fb35-11e6-89b7-7cfd67a2dc58.png)

![pic2](https://cloud.githubusercontent.com/assets/651179/23331527/c895e692-fb35-11e6-8483-9849b501ce06.png)

**Comment by orphu** [comment]
Hey, so thinking about it, the meta material approach will be great. 

One request I think, is that you make sure the materials are radially symmetrical around the center of the current chunk. That will make it easier to create all sorts of layered patterns in a room.

**Comment by JiFish** [comment]
Ironically, I have just this minute rolled back my meta material changes. The problem I was having was that meta-materials cannot, as far as I can work out, be configured on the fly. This caused me to pre-setup all the versions I could possibility need. Which worked, but I was less and less happy with as I went on.

I suspect I might have missed a trick here. I'm going to go ahead and push my experimental branch up to the project so you can see what I was thinking.

I'd be happy for you to pick this one up from here, if that's something you wanted to do? I think you have a stronger idea of how it should work than I do.

**Comment by JiFish** [comment]
Need to think about what colours to keep. The pinks and purples have got to go. (In normal rooms at least.)

**Comment by JiFish** [comment]
Damaged Mosaics should be more damaged than normal floors.

**Comment by orphu** [comment]
I saw your change to the ruin function. Seemed like the right approach. How'd that work out?

**Comment by JiFish** [comment]
It actually worked out really well. I like the way the there more damage at the edges of the floor. I'd noticed this with the existing floor types, but increasing that value make the effect more obvious.

**Comment by JiFish** [comment]
There's more that can be done with this, but I will mark as done for now.
