### ISSUE TITLE
Maps are BLANK for dungeons or treasure hunts

### ISSUE THREAD

**Issue by night-triumph** [orphu/mcdungeon#411]
Running Spigot 1.11.2 with multiverse.
Plugins: acceptrules, chairstairs, citizens, core protect, denizen, essentials2, essentials-chat, essentials-spawn, FastAsyncWorldEdit, GriefPrevention, imageonmap, lagmonitor, libdisguises, Multiverse-Core, Multiverse-Portals, Multiverse-NetherPortals, MythicMobs, namecolor, noswear, paradiseland, perworldinventory, permissionsex, protocolLib, SaneEconomy, Sentry, SignShop, TimedCommands, Vault, WorldBorder, WorldEdit, WorldGuard, InvRestore, SB-Skylands

My Process:
I pre-gen the map in single player, then I use a command block contraption to teleport around to expand the terrain on the map. Once that is done I run MCDungeon on the save file using the Windows executable.

I have tried with and without the Bukkit Server option using the name World, and even downloaded the main World level files from my server to see if that would help MCDungeon have a reference to generate the dungeon and treasure maps correctly. None of it worked - they still come up blank. This also happens with all of your paintings too.

The only time I have been able to see the generated dungeon and treasure maps has been after running MCDungeon with no Bukkit server world name, and playing it on single player. If I upload the same map to my server, the maps are blank.

Any help with this would be fantastic. I love your program! It's how Minecraft was meant to be played!!!

**Comment by JiFish** [comment]
The problem isn't that mcdungeon needs the main world files as a reference.
The main world is where the map files are stored. You must upload both back
to the server after generation.

**Comment by orphu** [comment]
Yeah, it just that the map files themselves need to be stored in the main map directories, and mcdungeon needs to know which map slots are free. You should work with a copy of your main map and the map you are placing your dungeons into. 

Best to run it on the server if you can. (keep backups)
