### ISSUE TITLE
UnicodeEncodeError in Console (v0.17.1-win64)

### ISSUE THREAD

**Issue by Keeko100** [orphu/mcdungeon#412]
I've reinstalled MCDungeon 5 times now and have used versions 0.17.1 and 0.17.0. However, every time I run the program, the console gives me this output:
http://pastebin.com/5NiqK7bg
When I enter a key the console closes and nothing else happens.
The only mod I have installed is Optifine.
Edit: Also, in the console, it doesn't list all my worlds. What's weird is that I've removed some of the worlds from my save file and it gives the same error. So say I deleted 'Copy of Mesa!' because I thought it was causing the problem. Now, it would list all worlds until 'Copy of Copy of Mesa!' and nothing after that. The same error would occur, however.

**Comment by JiFish** [comment]
This is a duplicate of known issue #335 

As a work-around, temporarily remove all worlds with unusual characters in their directory names. Or use the add command instead of interactive mode: http://mcdungeon-docs.bubblemod.org/en/latest/downloading-running/#add-mode

**Comment by Keeko100** [comment]
Thank you!
