### ISSUE TITLE
WARN Skipping Entity with id minecraft:customknight

### ISSUE THREAD

**Issue by Gaxan** [orphu/mcdungeon#414]
WARN Skipping Entity with id minecraft:customknight 
Spams the console and several spawners are empty.
Spigot 1.11.2 current build
no plugins

**Comment by Gaxan** [comment]
I'm actually getting the error for all the custom spawners

**Comment by JiFish** [comment]
Is the spawn folder present and full of files, e.g. `customknight.nbt`?

**Comment by Gaxan** [comment]
Yes, the spawned folder and all .nbt files are present in the bin folder.

**Comment by JiFish** [comment]
Do you know if file items e.g. `firework_classic.nbt` are working in loot chests?

There have been some changes to the way we load these in the development branch. Are you able to try the development branch?

**Comment by Gaxan** [comment]
I do recall seeing a santas or similar firework in a loot chest. 
I am not familiar with the development branch but can look at it when I get home today. I will also try regenerating some of the dungeons with these spawners in them. 
The map has over 400 dungeons and over 100 treasure hunts.

**Comment by Gaxan** [comment]
When attempting to regenerate the dungeons. McDungeon crashes after around 300 or so dungeons.
I've not had much luck getting numpy installed even after installing pip to try the development branch.

**Comment by Gaxan** [comment]
I remade a few dungeons on a new map with only the custom mobs.
Armored skeleton with iron sword does not spawn
Customknight does not spawn
Armored skeleton with axe spawns
fast zombie and stron zombie works

**Comment by orphu** [comment]
I would not recommend using the dev branch on a 1.11.2 world or game. Changes have already been made that require snapshot builds in MC. 

There may have been bugs with those spawners that were fixed in the new version. But you need to run a snapshot to get the fixes unfortunately. 

In MC 1.11.x and MCD 1.17.1 I'd recommend turning off custom spawners as I'm pretty sure they are broken. Try again when the new version comes out.

**Comment by Gaxan** [comment]
Thanks, looking forward to the new version

**Comment by orphu** [comment]
Going to close this since I'm pretty sure it will be fixed in the next version. You can remove all the NBT type spawners for now if you need.
