### ISSUE TITLE
Any plans to update at all? Been months since a release.

### ISSUE THREAD

**Issue by PsychoNavigator** [orphu/mcdungeon#419]

**Comment by JiFish** [comment]
Maybe not. I am unfamiliar with the build process and orphu has doesn't have the available free time he once did. If anyone wants to assist me with a build, I will look in to it.

The development branch does support the most recent version of Minecraft.

**Comment by PsychoNavigator** [comment]
You probably see my other issue then. I've edited it a few times so a refresh might be good if you havent yet. Sorry for clogging this up.

**Comment by orphu** [comment]
I'm still around-ish. Keep meaning to push out a build. It's fairly straight forward. There are scripts in extras for pyinstaller with instructions in the comments. I can push a build for 1.12, but it will be largely untested. 

I was having fun with some new treasure rooms for a bit, but they are incomplete.

**Comment by JiFish** [comment]
> but it will be largely untested

This is always annoying. I don't mind keeping it up-to-date with the new versions of 
Minecraft, but I never have enough time for rigorous testing. :/

**Comment by mathuin** [comment]
I am *not* volunteering to help at this point (my wife would _kill_ me) but how much of your testing is "run around and see if anything looks funny" versus "the block at X, Y, Z should have the following data values"?  For my project, the more I was able to nail down the specifics the better my tests became.

**Comment by JiFish** [comment]
@mathuin It's the former. When Minecraft updates, it normally makes subtle changes to the NBT structure and command format. We update based on the (often lacking) change logs. But the only way to check everything is working is to play through a bunch of dungeons.

When problems are introduced they are often subtle complications arising from internal changes at Minecraft's end. Not the easiest thing to test for even when you _are_ looking...

**Comment by orphu** [comment]
I've uploaded a v0.18.0 release compatible with Minecraft 1.12. The OSX build is failing at the moment. I'll have to look at it later. 

Sorry to be so absent these days. :(

**Comment by orphu** [comment]
As far as testing, yeah, a large amount of it is running around to make sure things look or work right. Sometimes command block change in unexpected ways, and traps or mechanisms fail to work as expected. 

I have a few scripts to build dungeons over and over with various permutations of the settings to attempt to find most of the show stopper bugs.
