### ISSUE TITLE
IndentationError and I am confused. 

### ISSUE THREAD

**Issue by CLGREEN94** [orphu/mcdungeon#421]
Hello, I was wondering if someone could point me in the right direction. I have a ex-staff member that made a script with mcdungeons now when I run the script it does everything but when it gets to dealing with McDungeon's it throws the following.. 

Could someone just point me in the correct direction to fix this? It would be much appreciated. 

https://puu.sh/xk7HM/dcdacb3b85.txt

**Comment by JiFish** [comment]
OK, this isn't a MCDungeon question, it's a python programming question. I am assuming you are not a python programmer. 

This problem doesn't occur in our codebase so there are two possibilities:

1. The script has become accidentally altered or corrupted. Restore from an earlier backup. You could consider upgrading to the latest version, but that will require you to look in to how MCDungeon is actually used.

2. The staff member in question made his/her own modifications to MCDungeon. In which case we cannot help.
