### ISSUE TITLE
TBDException with "malformed chunks" when running MCDungeon launcher 0.18

### ISSUE THREAD

**Issue by Arkanu-of-Galatiel** [orphu/mcdungeon#435]
I keep getting the following error when trying to generate dungeons:

> Pass 2:   0%[>                                                        ] TBDExcep
> tion in main loop. Exception info below:
> Traceback (most recent call last):
>   File "mcdungeon\mcdungeon.py", line 2177, in <module>
>   File "mcdungeon\mcdungeon.py", line 2008, in main
>   File "mcdungeon\mcdungeon.py", line 681, in loadCaches
>   File "mcdungeon\mcdungeon.py", line 600, in checkDInfo
>   File "mcdungeon\pymclevel\infiniteworld.py", line 1486, in getChunk
>   File "mcdungeon\pymclevel\infiniteworld.py", line 1448, in _getChunkData
>   File "mcdungeon\pymclevel\nbt.py", line 519, in load
>   File "mcdungeon\pymclevel\nbt.py", line 543, in _load_buffer
>   File "mcdungeon\pymclevel\nbt.py", line 298, in load_from
>   File "mcdungeon\pymclevel\nbt.py", line 298, in load_from
>   File "mcdungeon\pymclevel\nbt.py", line 298, in load_from
> ChunkMalformed: Chunk (-104, 145) had an error: KeyError(146,)
> 
> Press any key to continue . . .

I'm using Mcdungeon 0.18 win64 executable, and the target world is in minecraft version 1.13

Thank you for your time.

**Comment by JiFish** [comment]
Sorry, the last supported version of Minecraft is 1.12.

This project is on indefinite hold due to a change in the world format between 1.12 and 1.13. See issue #426 if you want to weigh in.
