### ISSUE TITLE
mcdungeon not working

### ISSUE THREAD

**Issue by DilanRona** [orphu/mcdungeon#436]
Tried to create a dungeon. Have a 1.12 world ready, and downloaded mcdungeon-v0.18.0. Failed to generate dungeons everytime.

python mcdungeon.py interactive
MCDungeon 0.18.0
Loaded 451 materials.
/home/rupert/src-build/mcdungeon/pymclevel/materials.py:166: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  blockyaml = yaml.load(f)
Loaded 734 items.
/usr/lib/python2.7/site-packages/nbt2yaml/yamlgen.py:171: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return _yaml_deserialize(yaml.load(stream))
firework_princess.yaml is an invalid item! Skipping.
firework_creeper.yaml is an invalid item! Skipping.
spellbook_fireball.yaml is an invalid item! Skipping.
head_villager.yaml is an invalid item! Skipping.
head_block_pumpkin.yaml is an invalid item! Skipping.
head_block_oaklog.yaml is an invalid item! Skipping.
magic_box_stone.yaml is an invalid item! Skipping.
head_golem.yaml is an invalid item! Skipping.
head_slime.yaml is an invalid item! Skipping.
head_block_chest.yaml is an invalid item! Skipping.
head_notch.yaml is an invalid item! Skipping.
head_jeb.yaml is an invalid item! Skipping.
head_mooshroom.yaml is an invalid item! Skipping.
head_sign_arrowup.yaml is an invalid item! Skipping.
head_sign_question.yaml is an invalid item! Skipping.
head_ocelot.yaml is an invalid item! Skipping.
head_cow.yaml is an invalid item! Skipping.
head_sign_exclamation.yaml is an invalid item! Skipping.
head_sshipway.yaml is an invalid item! Skipping.
head_dinnerbone.yaml is an invalid item! Skipping.
head_sign_arrowright.yaml is an invalid item! Skipping.
head_grumm.yaml is an invalid item! Skipping.
head_sign_arrowdown.yaml is an invalid item! Skipping.
head_block_coconut_green.yaml is an invalid item! Skipping.
head_chicken.yaml is an invalid item! Skipping.
magic_box_redstone.yaml is an invalid item! Skipping.
head_alex.yaml is an invalid item! Skipping.
head_jifish.yaml is an invalid item! Skipping.
firework_festive.yaml is an invalid item! Skipping.
head_jonkagstrom.yaml is an invalid item! Skipping.
head_orphu.yaml is an invalid item! Skipping.
head_zombiepigman.yaml is an invalid item! Skipping.
firework_classic.yaml is an invalid item! Skipping.
head_cavespider.yaml is an invalid item! Skipping.
head_irongolem.yaml is an invalid item! Skipping.
head_block_tnt.yaml is an invalid item! Skipping.
firework_golden.yaml is an invalid item! Skipping.
head_spider.yaml is an invalid item! Skipping.
firework_shower.yaml is an invalid item! Skipping.
firework_smoke.yaml is an invalid item! Skipping.
head_block_melon.yaml is an invalid item! Skipping.
head_ghast.yaml is an invalid item! Skipping.
head_block_cactus.yaml is an invalid item! Skipping.
head_sheep.yaml is an invalid item! Skipping.
sword_of_sharpness.yaml is an invalid item! Skipping.
head_blaze.yaml is an invalid item! Skipping.
spellbook_apples.yaml is an invalid item! Skipping.
firework_broke.yaml is an invalid item! Skipping.
magic_box_wood.yaml is an invalid item! Skipping.
head_pig.yaml is an invalid item! Skipping.
head_magmacube.yaml is an invalid item! Skipping.
head_herobrine.yaml is an invalid item! Skipping.
head_sign_arrowleft.yaml is an invalid item! Skipping.
firework_patriot.yaml is an invalid item! Skipping.
head_squid.yaml is an invalid item! Skipping.
firework_pineapple.yaml is an invalid item! Skipping.
head_block_coconut_brown.yaml is an invalid item! Skipping.
head_enderman.yaml is an invalid item! Skipping.
head_block_cake.yaml is an invalid item! Skipping.
Loaded 0 items from yaml files.
Starting interactive mode!

Then it detects my minecraft world.

Worlds in your save directory:

	[1] New World

Only one world available.

Choose an action:
-----------------

	[a] Add new dungeon(s) to this map.
	[t] Add new treasure hunt(s) to this map.
	[l] List dungeons and treasure hunts already in this map.
	[d] Delete dungeons or treasure hunts from this map.
	[r] Regenerate a dungeon or treasure hunt in this map.
	[p] Generate OverViewer POI file for dungeons and treasure hunts
	    already in this map.
	[w] Generate a WorldGuard regions file for dungeons already in
	    this map.

Enter choice or q to quit: a

Configurations in your configs directory:

	[1] default
	[2] maze
	[3] hard_mode
	[4] more_mobs
	[5] caverns
	[6] easy_mode

Choose a config (enter for default): 3
Reading config from /home/rupert/src-build/mcdungeon/configs/hard_mode.cfg ...
Loaded 17 dye colors.
Loaded 70 custom potions.
Loaded 72 magic items.
Loaded 12 shops.
Loaded 19 custom spawners.

Some configurations may generate dungeon maps. If you are
using multiverse you need supply the name of your
primary world for this to work. You can also provide this
in the config file or as a command switch.

(if you don't use multiverse, just hit enter)
Name of primary multiverse world: 

Enter the maximum distance (in chunks) from spawn to place
dungeons. Take care to pick a value that matches your needs.
If this value is too high and you add few dungeons, they
may be hard to find. If this value is too low and you
add many dungeons, they will not cover much of the map.

Max Distance (leave blank for config value, 20): 

Enter the size of the dungeon(s) in chunks from West to East. (X size)
You can enter a fixed value >= 4, or a range (ie: 4-7)

X size: 7

Enter the size of the dungeon(s) in chunks from North to South. (Z size)
You can enter a fixed value >= 4, or a range (ie: 4-7)

Z size: 7

Enter a number of levels.
You can enter a fixed value between 1 and 42, or a range (ie: 3-5)

Levels: 9

Enter the maximum number of dungeons to add.
Depending on the characteristics of your world, and size  of your
dungeons, the actual number placed may be less.
Enter -1 to add as many dungeons as possible.

Number of dungeons (enter for 1): -1
Trying to open: /home/rupert/.minecraft/saves/New World
Loaded world: /home/rupert/.minecraft/saves/New World (692 chunks, 256 blocks high)
Looking for data directory...
Reading loot tables...
Unknown item: file_firework_classic
ERROR: Tried to reference loot that does not exist.

And then it stops. No dungeons created.

Tested again by downloading the github version, same result. same error

Dilan

**Comment by DilanRona** [comment]
meh... no responce....
;

**Comment by JiFish** [comment]
It appears that pyyaml has updated since this project has gone inactive. I did put looking up the last known good version of pyyaml on my todo list, but since my reply wasn't fast enough for you I'll leave that as an exercise for the reader.

**Comment by DilanRona** [comment]
Honestly I though you were not interested.

    On Thursday, 28 March 2019, 21:49:03 GMT+2, Joseph Fowler <notifications@github.com> wrote:  
 
 
It appears that pyyaml has updated since this project has gone inactive. I did put looking up the last known good version of pyyaml on my todo list, but since my reply wasn't fast enough for you I'll leave that as an exercise for the reader.
