### ISSUE TITLE
Dungeon Maps?

### ISSUE THREAD

**Issue by orphu** [orphu/mcdungeon#72]
I was looking over the map item format and was thinking it would be cool to have maps of the dungeon levels that you could find in game.

You can make maps that are 1:1 in scale, meaning one map could cover an 8x8 dungeon level, or 1:2 could cover up to 16x16. 

Some ideas:
- The offset could possibly relate to the actual location so that the player position is shown on the map. I'm not sure how placing blocks would affect this... it may overwrite parts of the map with overland terrain. ...or....
- Maybe make the offset some crazy value way off map to prevent anything from being changed. Testing is needed. 
- Scale maps according to the dungeon size. 4-8 == 1:1, 9-16 == 1:2, 17-31 == 1:3, etc. If the offset was way off map this wouldn't matter too much. 
- Downside is that this uses up map entries on a level every time it is used. Granted, there at 2^16 map entries available, but there may need to be some mechanism for cleaning these out when regenerating or deleting dungeons. 

Some references:

http://www.minecraftwiki.net/wiki/Map_Item_Format

https://github.com/Kroc/McMaps

**Comment by denemanow** [comment]
I've got a question:
If I regenerate my dungeon with all my maps stored, for example, in chest on level 3, will these maps lay in this chest or will these maps be placed again as with new dungeon?
Or if I'll keep maps in my inventory, will they be placed again in chest (new maps) or I can use these old maps?

**Comment by JiFish** [comment]
If you regenerate a dungeon, the contents of the chests is also regenerated. Map IDs are reused, so you may find maps in your inventory now reference different areas. This is unavoidable they way it is currently done. See https://github.com/orphu/mcdungeon/issues/72#issuecomment-8344871
