### ISSUE TITLE
File paths with non-standard characters don't work.

### ISSUE THREAD

**Issue by JiFish** [orphu/mcdungeon#85]
Reported on minecraftforum.net

Here is the dump: http://pastebin.com/VEC4h9Wp

Using the --dir switch to specify a path without non-standard characters is a workaround.

**Comment by orphu** [comment]
This may be fixed by 57a09605a5dd09e9603ab1262749191d85719693. Needs testing.

**Comment by JiFish** [comment]
Python 2.x itself seems to have issues with python and Unicode paths that are valid under windows. I think the only way to fix it would be to import unicode_literals from futures and make sure we account for unicode everywhere. A huge task.

Here's an example with the dir structure: C:\test\✂\test.txt
```
>>> os.listdir('c:/test')[0]
'?'
>>> os.listdir('c:/test/'+(os.listdir('c:/test')[0]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'c:/test/?/*.*'
```

**Comment by JiFish** [comment]
I'm making an executive decision to close this. 57a09605a5dd09e9603ab1262749191d85719693 fixed this for many foreign language characters, but Unicode will never be supported short of a major rewrite.
